---
title: "Habitat Chapter Occupancy Model V1"
author: "Anna Kurtin"
date: "`r Sys.Date()`"
output: html_document
---

*NOTE:* You'll need to re run the scripts that are creating the vegetation metrics before running the model. This will incorporate the fixes for the extremely tall rose at ELI-2 and the duplicate on AME-1 (already fixed AME-1 in the veg cleaning code)

Also, I would go back and take the average species richness per point within the sites with 3 monitoring points, otherwise I feel like these points will be biased to have a higher tree species richness

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jagsUI)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(coda)
library(janitor)
library(loo)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/6_Function_Scripts/Create_SiteColumn_fromPointID.R")
```

## Data Reading and Formatting

#### Cov 1: Native broadleaf tree species richness
*Associated Script: ./R_Scripts/3_Data_Wrangling_Tidying/Cleaning_Vegetation_Data/Create_Community_Comp.R*
```{R Read in Cov 1, out.width = "50%", out.height = "50%"}
tree_rich <- read.csv("./Data/Habitat_Model_Covariates/Occupancy_Covariates/2023_ARUSites_TreeSppRich_5-24.csv")
# Scale this covariate
tree_rich$spp_rich_scale <- scale(tree_rich$spp_richness)[,1]
tree_rich_fin <- tree_rich %>% select(site_id,spp_rich_scale)
# Look at the distribution 
hist(tree_rich_fin$spp_rich_scale, col = cuckoo_palette[1], main = "Distribution of Scaled Tree Species Richness")
```

#### Cov 2: Dominant shrub species community
*Associated Script: ./R_Scripts/3_Data_Wrangling_Tidying/Cleaning_Vegetation_Data/Create_Community_Comp.R*
```{R Read in Cov 2, out.width = "50%", out.height = "50%"}
shrub_com <- read.csv("./Data/Habitat_Model_Covariates/Occupancy_Covariates/2023_ARUSites_ShrubDominantCommunity_5-24.csv")
# Can't scale- categorical
shrub_com_fin <- shrub_com %>% select(site_id,dominant_community)
# Look at the distribution 
shrubcom_table <- shrub_com_fin %>% group_by(dominant_community) %>% summarize(n=n())
ggplot(shrubcom_table) + geom_bar(aes(x = dominant_community, y = n, fill = dominant_community),stat = "identity")+
  scale_fill_manual(values = c("floodplain" = palette_8[2],"misc_broadleaf" = palette_8[4], "upland" = palette_8[6], "invasive" = palette_8[8])) +theme_minimal()
```

#### Cov 3: Subcanopy Veg Avg Height
#### Cov 4: Subcanopy Veg Percent Cover
#### Cov 5: Subcanopy Veg Complexity 
*Associated Script: ./R_Scripts/3_Data_Wrangling_Tidying/Cleaning_Vegetation_Data/Create_Subcanopy_Metrics.R*
```{R Read in Subcanopy Veg, out.width = "50%", out.height = "50%"}
subcan_metrics <- read.csv("./Data/Habitat_Model_Covariates/Occupancy_Covariates/2023_ARUSites_SubCanopyMetrics_5-24.csv")

# Scale this covariate
subcan_metrics$avg_height_scale <- scale(subcan_metrics$avg_shrub_height)[,1]
# Look at the distribution 
hist(subcan_metrics$avg_height_scale , col = cuckoo_palette[1], main = "Distribution of Scaled Subcanopy Height")

subcan_metrics$shrub_cover_scale <- scale(subcan_metrics$shrub_pcover)[,1]
# Look at the distribution 
hist(subcan_metrics$shrub_cover_scale, col = cuckoo_palette[1], main = "Distribution of Scaled Subcanopy Percent Cover")

subcan_metrics$height_sd_scale <- scale(subcan_metrics$shrub_heigh_sd)[,1]
# Look at the distribution 
hist(subcan_metrics$height_sd_scale, col = cuckoo_palette[1], main = "Distribution of Scaled Subcanopy SD of Height")

# Select covariates for use in model 
shrub_metrics_fin <- subcan_metrics %>% select(site_id,avg_height_scale, shrub_cover_scale, height_sd_scale)
# How to simulate this data later?
test <- rnbinom(n=107, size=50, mu=3)
hist(test)
# As size increases, the "peak" of the graph gets more spread out
# as mu increases, the max of the graph increases and the peak is centered around that number
```

#### Cov 6: Overall Veg Density
```{R Read in Cov 6}

```

#### Cov 7: Canopy Height
```{R Read in Cov 7}


```

#### Cov 8: Canopy Density
```{R Read in Cov 8}


```