---
title: 'Occupancy Sub Model B Final1: Landscape Scale Covariates'
author: "Anna Kurtin"
date: "8/27/2024"
output: html_document
---

#### Explanation of Model

This model is me redoing the landscape scale submodel to streamline and clarify my covariate selection process for the final global model. Here is a list of  the previous iterations of this model (also on OneNote):

* Landscape Submodel 1: landscape scale percent canopy and subcanopy cover, naive detection model

* Landscape Submodel 2: landscape scale percent canopy and subcanopy cover, parameterized detection model after talking with Lisa and going off of her model building process which is to add on the parameterized detection model when building the state model.

I'll be using the same structure in this model, adding in the new data and the detection model with veg density as a covariate. 


#### Model structure:


**State Model:** with two covariates

$$
Z_i \sim Bernoulli(\psi_i | \alpha_1, \alpha_2)
$$

$$ \alpha_1: \text{Landscape percent canopy cover}$$

$$ \alpha_2: \text{Landscape percent subcanopy cover}$$

**Detection Model**: with 5 covariates (from detection submodel final 2)

$$
y_{ij} \sim Bernoulli(p_{ij}| \beta_1, \beta_2, \beta_3, \beta_4, \beta_{4Q})
$$

$$\beta_1: \text{vegetation density}$$ 

$$\beta_2: \text{background decibels}$$ 

$$\beta_3: \text{survey effort}$$ 

$$\beta_4: \text{survey start date}$$  

$$\beta_4Q: \text{quadratic effect of start date}$$ 


**Handling of NAs:** imputation for missing habitat parameters, skipping missing detection data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(patchwork)
library(ggdist)
library(beepr)
library(corrgram)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```

#### Read in data and look at distributions accross points

```{R}
# Load in most recent version of data
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/HabChap_DetOccCovsFull_SCALED_8-12.csv")
# Make a detection column
full_dat$bbcu <- apply(full_dat[2:7], 1, max, na.rm = TRUE)
```

### Visualize distribution of scaled covariates

```{R}
cancov <- full_dat %>% select(bbcu, pct_can_landsc)

cancov_p1 <- cancov %>% ggplot() + geom_histogram(aes(x = pct_can_landsc),fill = palette_8[8]) + theme_minimal()
cancov_p2 <- ggplot(cancov) + 
  geom_jitter(aes(x = pct_can_landsc, y = bbcu), color = palette_8[8], width = .05, height = .05) +
  geom_smooth(aes(x = pct_can_landsc, y = bbcu), color = palette_8[8], se = FALSE, method = "glm", method.args = list(family = "binomial")) +
  labs(x = "% Canopy Cover", y = "Detection") + 
  scale_y_continuous(breaks = seq(0, 1, by = 1)) +
  theme_minimal()
```

```{R}
subcancov <- full_dat %>% select(bbcu, pct_subcan_landsc)

subcancov_p1 <- subcancov %>% ggplot() + geom_histogram(aes(x = pct_subcan_landsc),fill = palette_8[6]) + theme_minimal()
subcancov_p2 <- ggplot(subcancov) + 
  geom_jitter(aes(x = pct_subcan_landsc, y = bbcu), color = palette_8[6], width = .05, height = .05) +
  geom_smooth(aes(x = pct_subcan_landsc, y = bbcu), color = palette_8[6], se = FALSE, method = "glm", method.args = list(family = "binomial")) +
  labs(x = "% Subcanopy Cover", y = "Detection") + 
  scale_y_continuous(breaks = seq(0, 1, by = 1)) +
  theme_minimal()
```

```{R Visualize Quest}
cancov_p2 + subcancov_p2
```

```{R Visualize Correalations, warnings = FALSE, message = FALSE}
corrdat <- full_dat %>% select(pct_can_landsc, pct_subcan_landsc)
corrgram(corrdat, order=TRUE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Landscape Scale Occupancy Metrics")
```


#### Set up model

```{R Set up Data}
detections <- full_dat[,2:7]

# Have to specify the z data for a true presence if there was a 1 at any time 
z_dat <- rowSums(detections, na.rm = T)
z_dat[z_dat > 1] <- 1
z_dat[z_dat == 0] <- NA

# get the length of non-nas in the detection data
get_na <- function(x){(max(which(!is.na(x))))}
# Apply this to our data
miss <- apply(detections, 1, get_na)

# Detection covariates
veg <- full_dat$veg_density_avg_scaled
dates <- full_dat[,37:42]
effort <- full_dat[,31:36]
backdb <- full_dat[,24:29]
```

$$ \alpha_1: \text{Landscape percent canopy cover}$$

$$ \alpha_2: \text{Landscape percent subcanopy cover}$$

```{R}
# Create a list of data for JAGS
jags_data <- list(
  # True presence at sites with confirmed presences
  Z = z_dat,
  # Detection/nondetection data
  det_data = detections,
  # Veg density
  covb1 = veg,
  # Background noise
  covb2 = backdb,
  # Effort 
  covb3 = effort,
  # Date
  covb4 = dates,
  # % Canopy cover
  cova1 = cancov[,2],
  # % Subcanopy cover
  cova2 = subcancov[,2],
  n_unit = nrow(detections),
  miss = miss
)

# Set initial values \
init_func <- function(){
  list(
    a0 = rnorm(1, 0, 1),
    a1 = rnorm(1, 0, 1),
    a2 = rnorm(1, 0 ,1),
    b0 = rnorm(1, 0, 1),
    b1 = rnorm(1, 0, 1),
    b2 = rnorm(1, 0 ,1),
    b3 = rnorm(1, 0, 1),
    b4 = rnorm(1, 0, 1),
    b4Q = rnorm(1, 0, 1)
  )
}
```


```{R, echo = TRUE, eval = FALSE}
cat("
  model{
        # Priors
    a0 ~ dlogis(0, 1)
    a1 ~ dlogis(0, 1)
    a2 ~ dlogis(0, 1)
    b0 ~ dlogis(0, 1)
    b1 ~ dlogis(0, 1)
    b2 ~ dlogis(0, 1)
    b3 ~ dlogis(0, 1)
    b4 ~ dlogis(0, 1)
    b4Q ~ dlogis(0, 1)
  
    # Likelihood
    # Loop through each sampling unit
    for(i in 1:n_unit){
      # Impute missing habitat data
      covb1[i] ~ dnorm(0, 1)
      cova1[i] ~ dnorm(0, 1)
      cova2[i] ~ dnorm(0, 1)
  
      Z[i] ~ dbern(psi[i])  # Presence or absence drawn from a bernoulli distribution with occupancy probability psi  
      logit(psi[i]) <- a0 + a1*cova1[i] + a2*cova2[i] 
      
      for(j in 1:miss[i]){
       # Impute missing detection data
        covb2[i,j] ~ dnorm(0, 1)
        covb3[i,j] ~ dnorm(0, 1)
        covb4[i,j] ~ dnorm(0, 1)
  
        det_data[i,j] ~  dbern(mu_p[i,j])  # Create probability density drawn for each site
        mu_p[i,j] <- Z[i]*theta[i,j]
        logit(theta[i,j]) <- p[i,j]
        p[i,j] <- b0 + b1*covb1[i] + b2*covb2[i,j] + b3*covb3[i,j] + b4*covb4[i,j] + b4Q*(covb4[i,j]^2)
  
        # Create detection data without NAs
        det_na[i,j] <- det_data[i,j]
         
        #Calculate Bayes p-value - plug the parameters into the equation for each sample of the posterior and use this to create new observations
        Presi[i,j] <- (det_na[i,j] - theta[i,j])^2 # Calculate squared residual of observed data
        y_new[i,j] ~ dbern(mu_p[i,j])             # Simulate observed data
        Presi_new[i,j] <- (y_new[i,j] - theta[i,j])^2 # Calculate squared residual error of simulated data
        
      }
    }
    
    # Derived parameters
    ## Calculate sum of squared residual errors for observed 
    for(i in 1:n_unit){
       sobs[i] <- sum(Presi[i,1:miss[i]])
       ssim[i] <- sum(Presi_new[i,1:miss[i]])
    }
    
    SSEobs <- sum(sobs[])
    SSEsim <- sum(ssim[])
    p_val <- step(SSEsim - SSEobs)
    
  }
  ", file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccMod_BFin1.txt")
```

```{R Run Model, eval = FALSE}
fit_BF1 <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccMod_BFin1.txt",
                 parameters.to.save = c("a0", "a1", "a2", "b0", "b1", "b3", "b4", "b4Q", "p_val", "SSEobs", "SSEsim"),
                 n.iter = 10000, 
                 n.burnin = 4000, 
                 n.chains = 3,
                 n.thin = 2,
                 inits = init_func)
beep()
saveRDS(fit_BF1,"C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Models_Ran_Outputs/StateSubModel_BFinal1.Rdata")
```

```{R read in model}
fit_BF1 <- readRDS("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Models_Ran_Outputs/StateSubModel_BFinal1.Rdata")
```

#### Evaluate model outputs

$$ \alpha_1: \text{Landscape percent canopy cover}$$

$$ \alpha_1: \text{Landscape percent subcanopy cover}$$


```{R Evaluate Model}
summary(fit_BF1)
tracedens_jags(fit_BF1, parmfrow = c(2,3))
```

#### Examine model fit:

```{R Make Inference on P Value}
plot(fit_BF1$sims.list$SSEobs,fit_BF1$sims.list$SSEsim,xlab="SSEobs",ylab="SSEsim")
abline(0,1,lwd = 2, col = "red")
print(paste0("P value is: ",round(fit_BF1$mean$p_val, 2)))
```

#### Posterior distributions and F statistics:

```{R Create Plots of Posterior Distribution}
# Plot posterior distribution
chains_bf1 <- jags_df(fit_BF1)
# Select the chains for our covariates of interest
chains_viol <- chains_bf1 %>% select(a1,a2)
# Rename them to be more interpretable
colnames(chains_viol) <- c("% Canopy Cover","% Subcanopy Cover")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("% Canopy Cover","% Subcanopy Cover"),names_to = "parameter", values_to = "values")

f_stat <- data.frame(
  parameter = c("% Canopy Cover","% Subcanopy Cover"),
  median_value = c(round(fit_BF1$f$a1,2), round(fit_BF1$f$a2,2))
)

# Create the slab interval plot
ggplot(data = chains_viol_long, aes(x = values, y = parameter, fill = parameter)) + 
  # Plot posterior distributions
  stat_slabinterval() +
  # Establish colors
  scale_fill_manual(values = c("% Canopy Cover"=palette_8[8], "% Subcanopy Cover" = palette_8[6])) +
  # Add a line for 0 to show overlap of posterior
  geom_vline(xintercept = 0) +
  # Remove background color from plots
  theme_minimal() +
  # Turn off the legend
  guides(fill = "none") +
  # Add median values as text labels
  geom_text(data = f_stat, aes(x = 3.5, y = parameter, label = median_value), color = "black", hjust = .6)  
```

#### Median effect sizes: 

```{R Transform Parameter Estimates}
# Transform median values from posterior distribution into probability 
psi <- round(plogis(fit_BF1$q50$a0), 3)
print(paste0("psi:", psi))

a1 <- round(plogis(fit_BF1$q50$a0 + fit_BF1$q50$a1), 3)
print(paste0("% Canopy landscape:", a1))

a2 <- round(plogis(fit_BF1$q50$a0 + fit_BF1$q50$a2), 3)
print(paste0("% Subcanopy landscape:", a2))
```


#### Check for correlated parameters

```{R Check Parameter Correlations}
# Create a matrix of the mcmc chains for each parameter
mat <- cbind(fit_BF1$sims.list$a0,fit_BF1$sims.list$a1,fit_BF1$sims.list$a2)
# run a correlation test on the chains - here, I'm looking for values that are larger than other values
r <- cor(mat)
r
# Only one that is larger is the correlation between a0 and a3 - what is the logic of these parameters being correlated? Is this really something we need to worry about?
```

#### Check the last eigenvalue for evidence of correlated parameters

```{R Check Eigenvalues}
# look at the information contained within the MCMC chains, if the last eigenvector is close to zero, you don't have a lot of information here, probably as a result of colinearity 
eigen(r)

```


### Interpreting output:

**Strongly significant covariates (CI doesn't overlap 0): **

* Percent subcanopy cover landscape: There is an 100% chance that the true effect of subcanopy cover at a landscape (1km) scale on BBCU probability of use during the breeding season is negative. The median estimate for the effect of subcanopy cover on use transformed into probability space is is 0.065, which means that for every 1 sd increase in percent subcanopy cover above the mean (increase of 8 percentage points over the mean of 16 percentage points), the probability of use by a BBCU decreases by 6.5%.

**Weakly significant covariates (F > .70):** 

* Percent canopy cover landscape: There is a 97% chance that the true effect of canopy cover at a landscape (1 km ) scale on BBCU probability of use during the breeding season is positive. The median estimate for the effect of canopy cover on use transformed into probability space is 0.254, which means that for every 1 sd increase in percent canopy cover above the mean (increase of 6 percentage points over mean of 7), the probability of use by BBCU increases by 25.4%.