---
title: 'Occupancy Sub Model A Final1: Point Scale Covariates'
author: "Anna Kurtin"
date: "8/27/2024"
output: html_document
---

#### Explanation of model: 

This model is me redoing the point scale submodel to streamline and clarify my covariate selection process for the final global model. Here is a list of  the previous iterations of this model (also on OneNote):

* Point Submodel 1: Deciduous tree species richness, broadleaf, invasive, upland, floodplain shrub community, naive detection model. 

* Point Submodel 2: Deciduous tree species richness, floodplain shrub community parameterized detection model with date, quadratic effect of date, average db, and effort after talking with Lisa and going off of her model building process which is to add on the parameterized detection model when building the state model.

* Point Submodel 3: Deciduous tree species richness, floodplain shrub community, conifer tree species richness, parameterized detection model with date, quadratic effect of date, average db, and effort. I went back and included conifer tree species richness because I realized we want to say something about species composition effects on occupancy and with the previous iterations we could only say something about deciduous tree richness not about conifer tree richness. 

I'll be combining all of these covaraites in this model sans invasive shrub type and upland. Based on ./R_Markdown/Evaluate_Distrib_ContCovs_ShrubComm.Rmd, the invasive shrub type has too little points, and upland is correlated with other covariates. Therefore, all the covariates included are deciduous tree species richness, conifer tree species richness, broadleaf shrub, and floodplain shrub.


#### Model structure:


**State Model:** with four covariates

$$
Z_i \sim Bernoulli(\psi_i | \alpha_1, \alpha_2, \alpha_3, \alpha_4)
$$

$$ \alpha_1: \text{Deciduous tree spp richness}$$

$$ \alpha_1: \text{Conifer tree spp richnesss}$$

$$ \alpha_1: \text{Floodplain shrub community}$$

$$ \alpha_1: \text{Broadleaf shrub community}$$


**Detection Model**: with 5 covariates (from detection submodel final 2)

$$
y_{ij} \sim Bernoulli(p_{ij}| \beta_1, \beta_2, \beta_3, \beta_4, \beta_{4Q})
$$

$$\beta_1: \text{vegetation density}$$ 

$$\beta_2: \text{background decibels}$$ 

$$\beta_3: \text{survey effort}$$ 

$$\beta_4: \text{survey start date}$$  

$$\beta_4Q: \text{quadratic effect of start date}$$ 


**Handling of NAs:** imputation for missing habitat parameters, skipping missing detection data


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(patchwork)
library(ggdist)
library(beepr)
library(corrgram)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```

#### Read in data and look at distributions accross points

```{R}
# Load in most recent version of data
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/HabChap_DetOccCovsFull_SCALED_8-12.csv")
# Make a detection column
full_dat$bbcu <- apply(full_dat[2:7], 1, max, na.rm = TRUE)
```

### Visualize distribution of scaled covariates

```{R}
drich <- full_dat %>% select(bbcu, dtree_spp_rich)
drich_p1 <- drich %>% ggplot() + geom_histogram(aes(x = dtree_spp_rich),fill = palette_8[1]) + theme_minimal()
drich_p2 <- ggplot(drich) + 
  geom_jitter(aes(x = dtree_spp_rich, y = bbcu), color = palette_8[1], width = .05, height = .05) +
  geom_smooth(aes(x = dtree_spp_rich, y = bbcu), color = palette_8[1], se = FALSE, method = "glm", method.args = list(family = "binomial")) +
  labs(x = "Deciduous Tree Spp Richness", y = "Detection") + 
  scale_y_continuous(breaks = seq(0, 1, by = 1)) +
  theme_minimal()
```

```{R}
crich <- full_dat %>% select(bbcu, ctree_spp_rich)
crich_p1 <- crich %>% ggplot() + geom_histogram(aes(x = ctree_spp_rich), fill = palette_8[2]) + theme_minimal()
crich_p2 <- ggplot(crich) + 
  geom_jitter(aes(x = ctree_spp_rich, y = bbcu), color = palette_8[2], width = .05, height = .05) +
  geom_smooth(aes(x = ctree_spp_rich, y = bbcu), color = palette_8[2], se = FALSE, method = "glm", method.args = list(family = "binomial")) +
  labs(x = "Conifer Tree Spp Richness", y = "Detection") + 
  scale_y_continuous(breaks = seq(0, 1, by = 1)) +
  theme_minimal()
```

```{R}
fshrub <- full_dat %>% select(bbcu, floodplain_shrub)
fshrub_p1 <- fshrub %>% ggplot() + geom_histogram(aes(x = floodplain_shrub), fill = palette_8[3]) + theme_minimal()
fshrub_p2 <- ggplot(fshrub) + 
  geom_jitter(aes(x = floodplain_shrub, y = bbcu), color = palette_8[3], width = .05, height = .05) +
  geom_smooth(aes(x = floodplain_shrub, y = bbcu), color = palette_8[3], se = FALSE, method = "glm", method.args = list(family = "binomial")) +
  labs(x = "Floodplain Shrub Community Dominant", y = "Detection") + 
  scale_y_continuous(breaks = seq(0, 1, by = 1)) +
  theme_minimal()
```

```{R}
bshrub <- full_dat %>% select(bbcu, broadleaf_shrub)
bshrub_p1 <- bshrub %>% ggplot() + geom_histogram(aes(x = broadleaf_shrub), fill = palette_8[4]) + theme_minimal()
bshrub_p2 <- ggplot(bshrub) + 
  geom_jitter(aes(x = broadleaf_shrub, y = bbcu), color = palette_8[4], width = .05, height = .05) +
  geom_smooth(aes(x = broadleaf_shrub, y = bbcu), color = palette_8[4], se = FALSE, method = "glm", method.args = list(family = "binomial")) +
  labs(x = "Floodplain Shrub Community Dominant", y = "Detection") + 
  scale_y_continuous(breaks = seq(0, 1, by = 1)) +
  theme_minimal()
```


```{R Visualize Data Distribution}
drich_p2 + crich_p2
fshrub_p2 + bshrub_p2
```

```{R Visualize Correalations, warnings = FALSE, message = FALSE}
corrdat <- full_dat %>% select(dtree_spp_rich, ctree_spp_rich, floodplain_shrub, broadleaf_shrub)
corrgram(corrdat, order=TRUE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Point Scale Occupancy Metrics")
```


#### Set up model


```{R Set up Data}
detections <- full_dat[,2:7]

# Have to specify the z data for a true presence if there was a 1 at any time 
z_dat <- rowSums(detections, na.rm = T)
z_dat[z_dat > 1] <- 1
z_dat[z_dat == 0] <- NA

# get the length of non-nas in the detection data
get_na <- function(x){(max(which(!is.na(x))))}
# Apply this to our data
miss <- apply(detections, 1, get_na)


# Detection covariates
veg <- full_dat$veg_density_avg_scaled
dates <- full_dat[,37:42]
effort <- full_dat[,31:36]
backdb <- full_dat[,24:29]
```

$$ \alpha_1: \text{Deciduous tree spp richness}$$

$$ \alpha_2: \text{Conifer tree spp richnesss}$$

$$ \alpha_3: \text{Floodplain shrub community}$$

$$ \alpha_4: \text{Broadleaf shrub community}$$

```{R}
# Create a list of data for JAGS
jags_data <- list(
  # True presence at sites with confirmed presences
  Z = z_dat,
  # Detection/nondetection data
  det_data = detections,
  # Veg density
  covb1 = veg,
  # Background noise
  covb2 = backdb,
  # Effort 
  covb3 = effort,
  # Date
  covb4 = dates,
  # Decid tree
  cova1 = drich[,2],
  # Conif tree
  cova2 = crich[,2],
  # Floodplain shrub
  cova3 = fshrub[,2],
  # Broadleaf shrub
  cova4 = bshrub[,2],
  n_unit = nrow(detections),
  miss = miss
)

# Set initial values \
init_func <- function(){
  list(
    a0 = rnorm(1, 0, 1),
    a1 = rnorm(1, 0, 1),
    a2 = rnorm(1, 0 ,1),
    a3 = rnorm(1, 0, 1),
    a4 = rnorm(1, 0, 1),
    b0 = rnorm(1, 0, 1),
    b1 = rnorm(1, 0, 1),
    b2 = rnorm(1, 0 ,1),
    b3 = rnorm(1, 0, 1),
    b4 = rnorm(1, 0, 1),
    b4Q = rnorm(1, 0, 1)
  )
}
```


```{R, echo = TRUE, eval = FALSE}
cat("
  model{
        # Priors
    a0 ~ dlogis(0, 1)
    a1 ~ dlogis(0, 1)
    a2 ~ dlogis(0, 1)
    a3 ~ dlogis(0, 1)
    a4 ~ dlogis(0, 1)
    b0 ~ dlogis(0, 1)
    b1 ~ dlogis(0, 1)
    b2 ~ dlogis(0, 1)
    b3 ~ dlogis(0, 1)
    b4 ~ dlogis(0, 1)
    b4Q ~ dlogis(0, 1)
  
    # Likelihood
    # Loop through each sampling unit
    for(i in 1:n_unit){
      # Impute missing habitat data
      covb1[i] ~ dnorm(0, 1)
      cova1[i] ~ dnorm(0, 1)
      cova2[i] ~ dnorm(0, 1)
      cova3[i] ~ dnorm(0, 1)
      cova4[i] ~ dnorm(0, 1)
  
      Z[i] ~ dbern(psi[i])  # Presence or absence drawn from a bernoulli distribution with occupancy probability psi  
      logit(psi[i]) <- a0 + a1*cova1[i] + a2*cova2[i] + a3*cova3[i] + a4*cova4[i]
      
      for(j in 1:miss[i]){
       # Impute missing detection data
        covb2[i,j] ~ dnorm(0, 1)
        covb3[i,j] ~ dnorm(0, 1)
        covb4[i,j] ~ dnorm(0, 1)
  
        det_data[i,j] ~  dbern(mu_p[i,j])  # Create probability density drawn for each site
        mu_p[i,j] <- Z[i]*theta[i,j]
        logit(theta[i,j]) <- p[i,j]
        p[i,j] <- b0 + b1*covb1[i] + b2*covb2[i,j] + b3*covb3[i,j] + b4*covb4[i,j] + b4Q*(covb4[i,j]^2)
  
        # Create detection data without NAs
        det_na[i,j] <- det_data[i,j]
         
        #Calculate Bayes p-value - plug the parameters into the equation for each sample of the posterior and use this to create new observations
        Presi[i,j] <- (det_na[i,j] - theta[i,j])^2 # Calculate squared residual of observed data
        y_new[i,j] ~ dbern(mu_p[i,j])             # Simulate observed data
        Presi_new[i,j] <- (y_new[i,j] - theta[i,j])^2 # Calculate squared residual error of simulated data
        
      }
    }
    
    # Derived parameters
    ## Calculate sum of squared residual errors for observed 
    for(i in 1:n_unit){
       sobs[i] <- sum(Presi[i,1:miss[i]])
       ssim[i] <- sum(Presi_new[i,1:miss[i]])
    }
    
    SSEobs <- sum(sobs[])
    SSEsim <- sum(ssim[])
    p_val <- step(SSEsim - SSEobs)
    
  }
  ", file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccMod_AFin1.txt")
```

```{R Run Model, eval = FALSE}
fit_AF1 <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccMod_AFin1.txt",
                 parameters.to.save = c("a0", "a1", "a2", "a3","a4", "b0", "b1", "b3", "b4", "b4Q","p_val", "SSEobs","SSEsim"),
                 n.iter = 10000, 
                 n.burnin = 4000, 
                 n.chains = 3,
                 n.thin = 2,
                 inits = init_func)
beep()
saveRDS(fit_AF1,"C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Models_Ran_Outputs/StateSubModel_AFinal1.Rdata")
```

```{R read in model}
fit_AF1 <- readRDS("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Models_Ran_Outputs/StateSubModel_AFinal1.Rdata")
```

#### Evaluate model outputs

$$ \alpha_1: \text{Deciduous tree spp richness}$$

$$ \alpha_2: \text{Conifer tree spp richnesss}$$

$$ \alpha_3: \text{Floodplain shrub community}$$

$$ \alpha_4: \text{Broadleaf shrub community}$$

```{R Evaluate Model}
summary(fit_AF1)
tracedens_jags(fit_AF1, parmfrow = c(2,3))
```

#### Examine model fit:

```{R Make Inference on P Value}
plot(fit_AF1$sims.list$SSEobs,fit_AF1$sims.list$SSEsim,xlab="SSEobs",ylab="SSEsim")
abline(0,1,lwd = 2, col = "red")
print(paste0("P value is: ",round(fit_AF1$mean$p_val, 2)))
```

#### Posterior distributions and F statistics:

```{R Create Plots of Posterior Distribution}
# Plot posterior distribution
chains_af1 <- jags_df(fit_AF1)
# Select the chains for our covariates of interest
chains_viol <- chains_af1 %>% select(a1,a2,a3,a4)
# Rename them to be more interpretable
colnames(chains_viol) <- c("Decid Spp Rich","Conif Spp Rich","Floodplain Shrub","Broadleaf Shrub")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("Decid Spp Rich","Conif Spp Rich","Floodplain Shrub","Broadleaf Shrub"),names_to = "parameter", values_to = "values")

f_stat <- data.frame(
  parameter = c("Decid Spp Rich", "Conif Spp Rich", "Floodplain Shrub", "Broadleaf Shrub"),
  median_value = c(round(fit_AF1$f$a1,2), round(fit_AF1$f$a2,2), round(fit_AF1$f$a3,2), round(fit_AF1$f$a4,2))
)

# Create the slab interval plot
ggplot(data = chains_viol_long, aes(x = values, y = parameter, fill = parameter)) + 
  # Plot posterior distributions
  stat_slabinterval() +
  # Establish colors
  scale_fill_manual(values = c("Decid Spp Rich"=palette_8[1], "Conif Spp Rich" = palette_8[2],"Floodplain Shrub"=palette_8[3], "Broadleaf Shrub" = palette_5[4], "quadratic date" = palette_8[5])) +
  # Add a line for 0 to show overlap of posterior
  geom_vline(xintercept = 0) +
  # Remove background color from plots
  theme_minimal() +
  # Turn off the legend
  guides(fill = "none") +
  # Add median values as text labels
  geom_text(data = f_stat, aes(x = 3.5, y = parameter, label = median_value), color = "black", hjust = .6)  
```

#### Median effect sizes: 

```{R Transform Parameter Estimates}
# Transform median values from posterior distribution into probability 
psi <- round(plogis(fit_AF1$q50$a0), 3)
print(paste0("psi:", psi))

a1 <- round(plogis(fit_AF1$q50$a1), 3)
print(paste0("Deciduous tree spp richness:", a1))

a2 <- round(plogis(fit_AF1$q50$a2), 3)
print(paste0("Conifer tree spp richness:", a2))

a3 <- round(plogis(fit_AF1$q50$a3), 3)
print(paste0("Floodplain shrub community:", a3))

a4 <- round(plogis(fit_AF1$q50$a4), 3)
print(paste0("Broadleaf shrub community:", a4))
```


#### Check for correlated parameters

```{R Check Parameter Correlations}
# Create a matrix of the mcmc chains for each parameter
mat <- cbind(fit_AF1$sims.list$a0,fit_AF1$sims.list$a1,fit_AF1$sims.list$a2,
             fit_AF1$sims.list$a3,fit_AF1$sims.list$a4)
# run a correlation test on the chains - here, I'm looking for values that are larger than other values
r <- cor(mat)
r
# Only one that is larger is the correlation between a0 and a4 - what is the logic of these parameters being correlated? Is this really something we need to worry about?
```

Need to potential check the correlation between parameters for a4 (broadleaf shrub) and a1 (decid tree spp rich)

#### Check the last eigenvalue for evidence of correlated parameters

```{R Check Eigenvalues}
# look at the information contained within the MCMC chains, if the last eigenvector is close to zero, you don't have a lot of information here, probably as a result of colinearity 
eigen(r)

```

### Interpreting output:

**Strongly significant covariates (CI doesn't overlap 0):** none

**Weakly significant covariates (F > .70):** 

* Native deciduous tree species richness: there is an 82% chance that the true parameter for this covariate's effect on the probability of habitat use during the breeding season is positive. The median estimate for this parameter converted to probability space is 0.563, which means that for every one standard deviation increase in deciduous tree species richness above the mean (0.92 spp increase above average of .96 species), the probability of use by BBCU increases by 56.3%.

* Native conifer tree spp richness: there is a 93% chance that the true parameter for this covariate's effect on the probability of habitat use during the breeding season is negative. The median estimate for this parameter converted to probability space is 0.355, which means that for every one standard deviation increase in conifer tree species richness above the mean (0.20 increase above a mean of 0.52), the probability of use by bbcu decreases by 35.5% 

* Shrub community dominated by floodplain shrub species (cottonwood and willow): there is a 89% chance that the true parameter for this covariate's effect on the probability of habitat use during the breeding season is negative. The median estimate for this parameter converted to probability space is 0.274, which means that for sites that have a floodplain species dominated shrub community, the probability of use by BBCU decreases by 27.4% compared to sites that don't have this dominant community.

* Shrub community dominated by broadleaf shrub (deciduous shrubs not cottonwood, willow, or invasive species): there is an 83% chance that the true parameter for this covariate's effect on the probability of habiat use during the breeding season is positive. The median estiate for this parameter converted to probability space is 0.631, which means that for sites that have a broadleaf species dominanted shrub community, the probability of use by BBCU increases by 63.1% compared to sites that don't have this dominant community. 
