---
title: "Habitat Chapter Modeling Update"
author: "Anna Kurtin"
date: " 2024-07-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(beepr)
library(corrgram)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```

#### Research Question: What vegetation characteristics are associated with black-billed cuckoo (BBCU) habitat use at the western edge of this species’ breeding range in Montana? 

#### Goal: exploratory/hypothesis generation since there are no formal studies in this region

#### Prediction: the following characteristics are important - vegetation structure, both in canopy and subcanopy complexity and height; density of woody vegetation, and vegetation species composition

For this chapter, I am creating an occupancy model using passive acoustic monitoring detections of BBCU in 2023 So far, I have been creating the process and state submodels separately, then I plan to combine them into a global model. My process/detection submodel has the following structure: 

$$
z_i \sim Bernoulli(\psi)
$$ 

$$
y_{ij} \sim Bernoulli(p| \beta_{date}, \beta_{date}^2,\beta_{avg db}, \beta_{effort})
$$

I am currently working on finding the best state/occupancy submodel. Andy, Erim, and I generated an a priori list of covariates that we believe affect BBCU occupancy:

* Percent canopy and subcanopy cover at a landscape scale (1 km radius around the monitoring point)

* Percent canopy and subcanopy cover at a core area within the home range scale (130 m radius around the monitoring point)

* Canopy height and subcanopy height at the core area scale

* Vertical complexity (measured by standard deviation) of subcanopy vegetation and all vegetation at the core area scale

* Native broadleaf tree species richness and dominant shrub community type at a point scale (from veg surveys conducted in an 11.3 m radius around the monitoring point)

Including separate covariates for each shrub community type, this is 13 covariates, which is too much to fit in a global model on our 107 sites of data. Additionally, there are several colinear covariates within this data. We decided to split the covariates up by scale and fit occupancy models on each of these submodels, then take the significant covariates from each submodel and combine into our global model. Hopefully this will reduce the number of covariates from 13 to 1 - 4 ish. 


```{R Read in Data, include = FALSE}
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/Occupancy_Covariates/DetHist_VegCovs_Scaled_7-24.csv")

```
```{R Correlations Within Data, echo = FALSE, message = FALSE}
corrdat <- full_dat %>% select(-veg_sd_resid)
corrdat <- corrdat[,12:20]
corrgram(corrdat, order=TRUE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Landscape Scale Metrics")
```


```{R set up JAGS data}
detections <- full_dat[,2:7]

# Have to specify the z data for a true presence if there was a 1 at any time 
z_dat <- rowSums(detections, na.rm = T)
z_dat[z_dat > 1] <- 1
z_dat[z_dat == 0] <- NA

# get the length of non-nas in the detection data
get_na <- function(x){(max(which(!is.na(x))))}
# Apply this to our data
miss <- apply(detections, 1, get_na)
```

### Brief summary: Submodel A Point Scale

Covariates included: 

* **a1:** broadleaf tree spp richness

* **a2:** broadleaf shrub community (snowberry/chokecherry, etc.)

* **a3:** invasive shrub community (tamarisk/russian olive)

* **a4:** upland shrub community (sage/greasewood)

* **a5:** flooplain shrub community (cottonwood/willows)


```{R Setup JAGS Data A1, include = FALSE}
# Create a list of data for JAGS
jags_data <- list(
  # True presence at sites with confirmed presences
  Z = z_dat,
  # Detection/nondetection data
  det_data = detections,
  # Native broadleaf tree spp richness
  cov1 = full_dat[,12],
  # Broadleaf shrub community
  cov2 = full_dat[,8],
  # Invasive shrub community 
  cov3 = full_dat[,9],
  # Upland shrub community
  cov4 = full_dat[,10],
  # Floodplain shrub community
  cov5 = full_dat[,11],
  n_unit = nrow(detections),
  miss = miss
)

# Set initial values 
init_func <- function(){
  list(
    a0 = rnorm(1, 0, 1),
    a1 = rnorm(1, 0, 1),
    a2 = rnorm(1, 0, 1),
    a3 = rnorm(1, 0 ,1),
    a4 = rnorm(1, 0, 1),
    a5 = rnorm(1, 0, 1),
    b0 = rnorm(1, 0, 1)
  )
}
```

```{R Sub Model A1 Structure, eval = FALSE}
cat("
  model{
        # Priors
    a0 ~ dlogis(0, 1)
    a1 ~ dlogis(0, 1)
    a2 ~ dlogis(0, 1) 
    a3 ~ dlogis(0, 1)
    a4 ~ dlogis(0, 1)
    a5 ~ dlogis(0, 1)
    b0 ~ dlogis(0, 1)
  
    # Likelihood
    # Loop through each sampling unit
    for(i in 1:n_unit){
      # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
      cov3[i] ~ dnorm(0, 1)
      cov4[i] ~ dnorm(0, 1)
      cov5[i] ~ dnorm(0, 1)
  
      Z[i] ~ dbern(psi[i])  # Presence or absence drawn from a bernoulli distribution with occupancy probability psi  
      logit(psi[i]) <- a0 + a1*cov1[i] + a2*cov2[i] + a3*cov3[i] + a4*cov4[i] + a5*cov5[i]
      
      for(j in 1:miss[i]){
        det_data[i,j] ~  dbern(Z[i]*theta[i,j])  # Create detection data drawn from a bernoulli distribution incorporating the true presence (Z) with probability of detection theta
        logit(theta[i,j]) <- b0
        
      }
    }
    
  }
  ", file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccModA1.txt")
```

```{R Run Model A1, echo = FALSE, results = FALSE}
fit_A1 <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccModA1.txt",
                 parameters.to.save = c("a0", "a1", "a2", "a3", "a4", "a5", "b0"),
                 n.iter = 10000, 
                 n.burnin = 4000, 
                 n.chains = 3,
                 n.thin = 2,
                 inits = init_func)
```
```{R, echo = FALSE}
print(fit_A1)
chains_a1 <- jags_df(fit_A1)
# Select the chains for our covariates of interest
chains_viol <- chains_a1 %>% select(a1,a2,a3,a4,a5)
# Rename them to be more interpretable
colnames(chains_viol) <- c("tree spp richness","broadleaf shrub","invasive shrub","upland shrub", "floodplain shrub")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("tree spp richness","broadleaf shrub","invasive shrub","upland shrub", "floodplain shrub"),names_to = "Parameter", values_to = "Values")

# Create the violin plot
ggplot() +
  geom_violin(data=chains_viol_long, aes(x = Parameter, y = Values,fill = Parameter),trim = FALSE) +
  labs(title = "Posterior Distribution of Point Level Covariates") +
  scale_fill_manual(values = c("tree spp richness"=palette_5[1], "broadleaf shrub" = palette_5[2],"invasive shrub"=palette_5[3], "upland shrub" = palette_5[4], "floodplain shrub" = palette_5[5])) + 
  geom_hline(yintercept = 0, linetype = "solid", color = "black") +
  theme_minimal()
```


### Brief summary: Submodel B Landscape Scale

Covariates included:

* **a1:** Percent canopy cover

* **a2:** Percent subcanopy cover


```{R Set up JAGS Data B1, include = FALSE}
# Create a list of data for JAGS
jags_data <- list(
  # True presence at sites with confirmed presences
  Z = z_dat,
  # Detection/nondetection data
  det_data = detections,
  # Percent canopy cover at landscape scale
  cov1 = full_dat[,13],
  # Percent subcanopy cover at landscape scale
  cov2 = full_dat[,14],
  n_unit = nrow(detections),
  miss = miss
)

# Set initial values 
init_func <- function(){
  list(
    a0 = rnorm(1, 0, 1),
    a1 = rnorm(1, 0, 1),
    a2 = rnorm(1, 0, 1),
    b0 = rnorm(1, 0, 1)
  )
}
```

```{R Sub Model B1 Structure, eval = FALSE}
cat("
  model{
        # Priors
    a0 ~ dlogis(0, 1)
    a1 ~ dlogis(0, 1)
    a2 ~ dlogis(0, 1)
    b0 ~ dlogis(0, 1)
  
    # Likelihood
    # Loop through each sampling unit
    for(i in 1:n_unit){
      # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
  
      Z[i] ~ dbern(psi[i])  # Presence or absence drawn from a bernoulli distribution with occupancy probability psi  
      logit(psi[i]) <- a0 + a1*cov1[i] + a2*cov2[i] 
      
      for(j in 1:miss[i]){
        det_data[i,j] ~  dbern(Z[i]*theta[i,j])  # Create detection data drawn from a bernoulli distribution incorporating the true presence (Z) with probability of detection theta
        logit(theta[i,j]) <- b0
        
      }
    }
    
  }
  ", file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccModB1.txt")
```

```{R Run Model B1, echo = FALSE, results = FALSE}
fit_B1 <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccModB1.txt",
                 parameters.to.save = c("a0", "a1", "a2", "b0"),
                 n.iter = 10000, 
                 n.burnin = 4000, 
                 n.chains = 3,
                 n.thin = 2,
                 inits = init_func)
```
```{R, echo = FALSE}
print(fit_B1)

chains_b1 <- jags_df(fit_B1)
# Select the chains for our covariates of interest
chains_viol <- chains_b1 %>% select(a1,a2)
# Rename them to be more interpretable
colnames(chains_viol) <- c("% canopy cover","% subcanopy cover")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("% canopy cover","% subcanopy cover"),names_to = "Parameter", values_to = "Values")

# Create the violin plot
ggplot() +
  geom_violin(data=chains_viol_long, aes(x = Parameter, y = Values,fill = Parameter),trim = FALSE) +
  labs(title = "Posterior Distribution of Landscape Level Covariates") +
  scale_fill_manual(values = c("% canopy cover"=palette_5[1], "% subcanopy cover" = palette_5[2])) + 
  geom_hline(yintercept = 0, linetype = "solid", color = "black") +
  theme_minimal()
```


### Brief summary: Submodel C Core Area Scale

I have a couple different iterations of this model already, but I'll show you the original one I started with. We decided to only deal with the strong colinearity (R = .90) between total vegetation SD and canopy height. We did this by using the residual variation in SD regressed against height instead of the original covariate. This way  so that we could see the unique contribution of the additional variation in veg complexity. 

Covariates included:

* **a1:** Percent canopy cover

* **a2:** Percent subcanopy cover

* **a3:** Canopy height 

* **a4:** Subcanopy height

* **a5:** subcanopy standard deviation

* **a6:** total vegetation standard deivation residual variation from regression with canopy height

```{R Setup JAGS Data C1, include = FALSE}
# Create a list of data for JAGS
jags_data <- list(
  # True presence at sites with confirmed presences
  Z = z_dat,
  # Detection/nondetection data
  det_data = detections,
  # percent canopy
  cov1 = full_dat$pct_can_core,
  # percent subcanopy
  cov2 = full_dat$pct_subcan_core,
  # canopy height
  cov3 = full_dat$ht_can_core,
  # subcanopy height
  cov4 = full_dat$ht_subcan_core,
  # subcanopy sd
  cov5 = full_dat$sd_subcan_core,
  # veg sd residual from canopy height
  cov6 = full_dat$veg_sd_resid,
  n_unit = nrow(detections),
  miss = miss
)

# Set initial values 
init_func <- function(){
  list(
    a0 = rnorm(1, 0, 1),
    a1 = rnorm(1, 0, 1),
    a2 = rnorm(1, 0, 1),
    a3 = rnorm(1, 0 ,1),
    a4 = rnorm(1, 0, 1),
    a5 = rnorm(1, 0, 1),
    a6 = rnorm(1, 0 ,1),
    b0 = rnorm(1, 0, 1)
  )
}
```


```{R Sub Model C1 Structure, eval = FALSE}
cat("
  model{
        # Priors
    a0 ~ dlogis(0, 1)
    a1 ~ dlogis(0, 1)
    a2 ~ dlogis(0, 1)
    a3 ~ dlogis(0, 1)
    a4 ~ dlogis(0, 1)
    a5 ~ dlogis(0, 1)
    a6 ~ dlogis(0, 1)
    b0 ~ dlogis(0, 1)
  
    # Likelihood
    # Loop through each sampling unit
    for(i in 1:n_unit){
      # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
      cov3[i] ~ dnorm(0, 1)
      cov4[i] ~ dnorm(0, 1)
      cov5[i] ~ dnorm(0, 1)
      cov6[i] ~ dnorm(0, 1)
  
      Z[i] ~ dbern(psi[i])  # Presence or absence drawn from a bernoulli distribution with occupancy probability psi  
      logit(psi[i]) <- a0 + a1*cov1[i] + a2*cov2[i] + a3*cov3[i] + a4*cov4[i] + a5*cov5[i] + a6*cov6[i]
      
      for(j in 1:miss[i]){
        det_data[i,j] ~  dbern(Z[i]*theta[i,j])  # Create detection data drawn from a bernoulli distribution incorporating the true presence (Z) with probability of detection theta
        logit(theta[i,j]) <- b0
        
      }
    }
    
    # Derived parameters
    
  }
  ", file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccModC1.txt")

```

```{R Run Model, echo = FALSE, results = FALSE}
fit_C1 <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Occupancy_Submodel/Model_Structure_Files/JAGS_HabOccModC1.txt",
                 parameters.to.save = c("a0", "a1", "a2", "a3", "a4", "a5", "a6", "b0"),
                 n.iter = 10000, 
                 n.burnin = 4000, 
                 n.chains = 3,
                 n.thin = 2,
                 inits = init_func)
```


```{R, echo = FALSE}
print(fit_C1)

chains_c1 <- jags_df(fit_C1)
# Select the chains for our covariates of interest
chains_viol <- chains_c1 %>% select(a1,a2,a3,a4,a5,a6)
# Rename them to be more interpretable
colnames(chains_viol) <- c("% canopy","% subcanopy","canopy height","subcanopy height", "subcanopy sd", "veg sd residual")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("% canopy","% subcanopy","canopy height","subcanopy height", "subcanopy sd", "veg sd residual"),names_to = "Parameter", values_to = "Values")

# Create the violin plot
ggplot() +
  geom_violin(data=chains_viol_long, aes(x = Parameter, y = Values,fill = Parameter),trim = FALSE) +
  labs(title = "Posterior Distribution of Core Area Scale Covariates") +
  scale_fill_manual(values = c("% canopy"=palette_8[1], "% subcanopy" = palette_8[2],"canopy height"=palette_8[3], "subcanopy height" = palette_8[4], "subcanopy sd" = palette_8[5], "veg sd residual" = palette_8[6])) + 
  geom_hline(yintercept = 0, linetype = "solid", color = "black") +
  theme(axis.text.x = element_text(angle = 45,hjust = 1))
```

After seeing these results, I mapped out colinearity relationships greater than R = .6 and created more residual variables to try to pick apart the importance of the total value of the covariate vs each of their unique contribution. I'd love to talk through a bit the process for picking apart these relationships and deciding how to account for them in models.

### Questions:

* What is the best way to address colinearity within models like this?

* What is the best way to pare down the number of covariates in a model?

* What is the best way of assessing goodness of fit when creating sub models like this? 