---
title: "Hab Chap Linear Model Final 3"
author: "Anna Kurtin"
date: "9/3/2024"
output: html_document
---

This is the third iteration of the linear model I will be using to test strength of habitat use across sites. Previous model parameterizatinos with a negative binomial distribution for the response variable didn't allow me to incorporate the sites with no BBCU calls, so I'm going to try to include those in this model and reparameterize it with a beta distribution. 

TODO: check Vlad's model for how they parameterized their linear model 

### Model structure

$$
\theta \sim Beta(\gamma_0 + \gamma_{1} + \gamma_{2} + \gamma_{3}  + \gamma_{4}  + \gamma_{5})
$$

$$ \gamma_{1}: \text{conifer spp richness} $$

$$ \gamma_{2}: \text{percent canopy cover on a landscape scale} $$

$$ \gamma_{3}: \text{percent subcanopy cover on a landscape scale} $$

$$ \gamma_{4}: \text{veg sd residuals on a core scale} $$

$$ \gamma_{5}: \text{percent subcanopy cover on a core scale} $$


**Handling of NAs (only occur in habitat covs):** Imputation 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(beepr)
library(corrgram)
library(ggdist)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```


### Visualize Data and Colinearity 

```{R Read in Data}
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/Linear_Model/HabChap_22-23_DaysCalls_HabCovs.csv")
# Round the percentage of days with calls
full_dat$pct_days_wcall <- round(full_dat$pct_days_wcall,0)
```

```{R Conifer Spp Richness}
ggplot(full_dat) + geom_point(aes(x = ctree_spp_rich, y = pct_days_wcall), size = 3, col = palette_5[1]) + 
  labs(x = "Conifer Tree Species Richness", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Pct Canopy Landsape}
ggplot(full_dat) + geom_point(aes(x = pct_can_landsc, y = pct_days_wcall), size = 3, color = palette_5[2]) + 
  labs(x = "% Canopy 1 km Radius", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Pct Suanopy Landsape}
ggplot(full_dat) + geom_point(aes(x = pct_subcan_landsc, y = pct_days_wcall), size = 3, color = palette_5[3]) + 
  labs(x = "% Subcanopy 1 km Radius", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Veg SD Residuals}
ggplot(full_dat) + geom_point(aes(x = veg_sd_resid, y = pct_days_wcall), size = 3, color = palette_5[4]) + 
  labs(x = "All Vegetation St Dev Residuals on Canopy Height", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Percent Subcanopy Core}
ggplot(full_dat) + geom_point(aes(x = pct_subcan_core, y = pct_days_wcall), size = 3, color = palette_5[5]) + 
  labs(x = "% Subcanopy 130 m Radius", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Look at Correlations, warnings = FALSE, message = FALSE}
corrdat <- full_dat %>% select(ctree_spp_rich, pct_can_landsc, pct_subcan_landsc, veg_sd_resid, pct_subcan_core)
corrgram(corrdat, order=TRUE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Habitat Metrics")
```

### Set up model 

```{R Format Data for JAGS}
days <-  full_dat$pct_days_wcall
n_unit <- nrow(full_dat)
# Transform days 
days <- (days * (n_unit - 1) + 0.5) / n_unit
# Transform to be between 0 and 1
pct_days <- days/100

# Create a list of data for JAGS
jags_data <- list(
  # Percentage of days with bbcu 
  days = pct_days,
  # Conifer spp richness
  cov1 = full_dat$ctree_spp_rich,
  # % canopy landscape
  cov2 = full_dat$pct_can_landsc,
  # % subcanopy landscape
  cov3 = full_dat$pct_subcan_landsc,
  # residual veg sd
  cov4 = full_dat$veg_sd_resid,
  # % subcanopy core
  cov5 = full_dat$pct_subcan_core,
  n_unit = nrow(full_dat)
)

# Set initial values 
init_func <- function(){
  list(
    a0 = rnorm(1, 0, 1), 
    a1 = rnorm(1, 0, 1),
    a2 = rnorm(1, 0, 1),
    a3 = rnorm(1, 0, 1),
    a4 = rnorm(1, 0, 1),
    a5 = rnorm(1, 0, 1)
  )
}
```

Is this parameterization of the model valid? Should I parameterize this more like my other models?

```{R, eval = FALSE}
cat("
  model {
    # Priors
    a0 ~ dnorm(0, 1)
    a1 ~ dnorm(0, 1)
    a2 ~ dnorm(0, 1)
    a3 ~ dnorm(0, 1)
    a4 ~ dnorm(0, 1)
    a5 ~ dnorm(0, 1)
    phi ~ dgamma(1, 1)  # Precision parameter for the beta distribution (phi is often used for this)

    # Likelihood
    for (i in 1:n_unit) {
      # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
      cov3[i] ~ dnorm(0, 1)
      cov4[i] ~ dnorm(0, 1)
      cov5[i] ~ dnorm(0, 1)

      # Beta regression
      mu_linear[i] <- a0 + a1*cov1[i] + a2*cov2[i] + a3*cov3[i] + a4*cov4[i] + a5*cov5[i]
      mu[i] <- ilogit(mu_linear[i])  # Inverse logit to ensure mu[i] is in the range (0,1)
      alpha[i] <- mu[i] * phi       # Shape parameter alpha
      beta[i] <- (1 - mu[i]) * phi  # Shape parameter beta

      days[i] ~ dbeta(alpha[i], beta[i])  # Beta distribution for days
  
      # Calculate squared residuals for observed data
      Presi[i] <- pow((days[i] - mu[i]), 2)

      # Simulate new data for posterior predictive checks
      y_new[i] ~ dbeta(alpha[i], beta[i])

      # Calculate squared residuals for replicated data
      Presi_new[i] <- pow((y_new[i] - mu[i]), 2)
    }
    
    # Derived parameters
    ## Sum of squared residual errors for observed and replicated data
    SSEobs <- sum(Presi[])
    SSEsim <- sum(Presi_new[])

    # Calculate Bayesian p-value
    p_val <- step(SSEsim - SSEobs)
  }
", file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLinearModFinal3.txt")

```


```{R, results = FALSE, eval = FALSE}
fit_beta <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLinearModFinal3.txt",
                 parameters.to.save = c("a0", "a1", "a2", "a3", "a4", "a5", "SSEobs", "SSEsim", "p_val"),
                 n.iter = 10000, 
                 n.burnin = 4000, 
                 n.chains = 3,
                 n.thin = 2,
                 inits = init_func)
beep()
saveRDS(fit_beta,"C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LModFinal3.Rdata")
```
```{R Read in Model}
fit_beta <- readRDS("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LModFinal3.Rdata")
```

```{R Evaluate Model}
summary(fit_beta)
tracedens_jags(fit_beta, parmfrow = c(2,2))
```


$$ \gamma_{1}: \text{conifer spp richness} $$

$$ \gamma_{2}: \text{percent canopy cover on a landscape scale} $$

$$ \gamma_{3}: \text{percent subcanopy cover on a landscape scale} $$

$$ \gamma_{4}: \text{veg sd residuals on a core scale} $$

$$ \gamma_{5}: \text{percent subcanopy cover on a core scale} $$

### Examine model fit:

```{R Make Inference on P Value}
plot(fit_beta$sims.list$SSEobs,fit_beta$sims.list$SSEsim,xlab="SSEobs",ylab="SSEsim")
abline(0,1,lwd = 2, col = "red")
print(paste0("P value is: ",round(fit_beta$mean$p_val, 2)))
```

Based off of the p value, this model is ok. However, I think I should go through and do a bit more checking of this model, make sure it's actually converging properly and is an adequate fit for the data. 


```{R Create Plots of Posterior Distribution}
# Plot posterior distribution
chains_beta <- jags_df(fit_beta)
# Select the chains for our covariates of interest
chains_viol <- chains_beta %>% select(a1, a2, a3, a4, a5)
# Rename them to be more interpretable
colnames(chains_viol) <- c("Conifer Spp Richness","% Canopy Cover Landscape", "% SUBCAN cover landscape", "Veg SD Resid Core", "% SUBCAN cover core")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("Conifer Spp Richness","% Canopy Cover Landscape", "% SUBCAN cover landscape", "Veg SD Resid Core", "% SUBCAN cover core"),names_to = "parameter", values_to = "values")

f_stat <- data.frame(
  parameter = c("Conifer Spp Richness",
                "% Canopy Cover Landscape", 
                "% SUBCAN cover landscape", 
                "Veg SD Resid Core", 
                "% SUBCAN cover core"),
  median_value = c(paste0("F: ",round(fit_beta$f$a1,2)), 
                   paste0("F: ",round(fit_beta$f$a2,2)),
                   paste0("F: ",round(fit_beta$f$a3,2)),
                   paste0("F: ",round(fit_beta$f$a4,2)),
                   paste0("F: ",round(fit_beta$f$a5,2)))
  )

# Create the slab interval plot
ggplot(data = chains_viol_long, aes(x = values, y = parameter, fill = parameter)) + 
  # Plot posterior distributions
  stat_slabinterval() +
  # Establish colors
  scale_fill_manual(values = c("Conifer Spp Richness" = palette_5[1], 
                               "% Canopy Cover Landscape" = palette_5[2],
                               "% SUBCAN cover landscape" = palette_5[3],
                               "Veg SD Resid Core" = palette_5[4], 
                               "% SUBCAN cover core" = palette_5[5])) +
  # Add a line for 0 to show overlap of posterior
  geom_vline(xintercept = 0) +
  # Remove background color from plots
  theme_minimal() +
  # Turn off the legend
  guides(fill = "none") +
  # Add median values as text labels
  geom_text(data = f_stat, aes(x = .5, y = parameter, label = median_value), color = "black", hjust = .5)  
```

```{R Gravy Yard}
# # Beta regression
#       mu[i] <- a0 + a1*cov1[i] + a2*cov2[i] + a3*cov3[i] + a4*cov4[i] + a5*cov5[i]
#       logit_mu[i] <- logit(mu[i])  # Logit link function
#       alpha[i] <- mu[i] * phi       # Shape parameter alpha
#       beta[i] <- (1 - mu[i]) * phi  # Shape parameter beta

```