---
title: "Hab Chap Linear Model Version 11: Gamma-Poisson Paramterization"
author: "Anna Kurtin"
date: "9/20/2024"
output: html_document
---

This is the eleventh iteration of the linear model I will be using to test strength of habitat use across sites. Using the gamma-poisson distribution to parameterize the response variable to account for not only how many days with calling but also how many days there are for each site. Trying to include all of the data including the zeros and all of the covariates of interest. 

### Model structure:

$$ c_i \sim Poisson(\gamma_i * h_i) $$

$$ h_i \sim Gamma(\theta,\theta) $$

$$ \theta \sim Gamma(1, 1) $$

$$ log(\gamma_i) = \beta_0 + \beta_1 * cov1 + \beta_2 * cov2 + \beta_3 * cov3 + \beta_4 * cov4 $$

$$ c_i: \text{Number of calls at a site}$$

$$ \beta_1: \text{Percent canopy cover at lanscape scale}$$

$$ \beta_2: \text{Percent shrub/early successional cover at landscape scale} $$

$$ \beta_3: \text{Vegetation sd residuals at core area scale} $$

$$ \beta_4: \text{Percent shrub/early successional cover at core area scale} $$

**Handling of NAs (only occur in habitat covs):** Imputation for habitat covariates (sites with no LiDAR data), no missing data for call counts


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(beepr)
library(corrgram)
library(ggdist)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```


### Visualize Data and Colinearity 

```{R Read in Data}
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/Linear_Model/HabChap_22-23_DaysCalls_HabCovs_9-12.csv")
```

*Ignore the warnings below*

```{R, warnings = FALSE, message = FALSE}
corrdat <- full_dat %>% select(pct_can_landsc, pct_openshrub_landsc, veg_sd_resid, pct_openshrub_core)
corrgram(corrdat, order=TRUE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Habitat Metrics")
```

### Set up model 

```{R Set up JAGS Data, echo = TRUE}
# Create a list of data for JAGS
jags_data <- list(
  # Percentage of days with bbcu 
  y = full_dat$days_wcall,
  # % canopy landscape
  cov1 = full_dat$pct_can_landsc,
  # % open shrub landscape
  cov2 = full_dat$pct_openshrub_landsc,
  # residual veg sd
  cov3 = full_dat$veg_sd_resid,
  # % open shrub core
  cov4 = full_dat$pct_openshrub_core,
  # number of days recorded at each site
  n = nrow(full_dat)
)
  
# Set initial values 
init_func <- function(){
  list(
    beta0 = rnorm(1, 0, 1), 
    beta1 = rnorm(1, 0, 1),
    beta2 = rnorm(1, 0, 1),
    beta3 = rnorm(1, 0, 1),
    beta4 = rnorm(1, 0, 1)
  )
}
```

```{R Create Model Structure, eval = FALSE, echo = TRUE}
sink("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLMod11_GamPois.jags")
cat("
    model {
    for (i in 1:n){
    
    # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
      cov3[i] ~ dnorm(0, 1)
      cov4[i] ~ dnorm(0, 1)
    
      # Method 2: gamma-poisson (this is equivalent to a negative binomial)
      # In this approach, the parameter of interest is the count of days with calls but we're also feeding it the number of days that we recorded 
      log(gamma[i]) = beta0 + beta1 * cov1[i] + beta2 * cov2[i] + beta3 * cov3[i] + beta4 * cov4[i]  
      h[i] ~ dgamma(theta, theta) # Variance in rate parameter
      y[i] ~ dpois(gamma[i] * h[i]) # count drawn from poisson distribution with adjusted rate parameter
    
      # Squared residuals for observed data
      presi[i] <- pow((y[i] - gamma[i]*h[i]),2)
      # Simulate new data
      y_new[i] ~ dpois(gamma[i]*h[i])
      # Squared residuals for simulated data
      presi_new[i] <- pow((y_new[i] - gamma[i]*h[i]),2)
      
    }
    # Priors
    theta ~ dgamma(1,1)
    beta0 ~ dnorm(0, 0.01)
    beta1 ~ dnorm(0, 0.01)
    beta2 ~ dnorm(0, 0.01) 
    beta3 ~ dnorm(0, 0.01)
    beta4 ~ dnorm(0, 0.01) 
    
    # Derived values
    SSEobs <- sum(presi[])
    SSEsim <- sum(presi_new[])
    # Bayesian p-value: proportion of times SSEsim > SSEobserved
    p_val <- step(SSEsim - SSEobs)

    }
    ",fill = TRUE)
sink()

```


```{R, results = FALSE, eval = FALSE, echo = TRUE}
fit_gpois <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLMod11_GamPois.jags",
                 parameters.to.save = c("beta0","beta1","beta2","beta3","beta4", "SSEobs","SSEsim", "p_val"),
                 n.iter = 40000, 
                 n.burnin = 20000, 
                 n.chains = 3,
                 n.thin = 10,
                 inits = init_func)
beep()
saveRDS(fit_gpois,"C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LMod11_GamPois.Rdata")
```
```{R Read in Model}
fit_gpois <- readRDS("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LMod11_GamPois.Rdata")
```

```{R Evaluate Model}
summary(fit_gpois)
tracedens_jags(fit_gpois, parmfrow = c(3,3)) 

# dig a bit more into gelman rubin diagnostic
# fit_mcmc <- fit_gpois$samples
# gelman.diag(fit_mcmc) # these look fine 

# Visualize colinearities between estimates and intercept
# parmfrow = c(2,2)
# plot(fit_gpois$sims.list$beta0, fit_gpois$sims.list$beta1)
# plot(fit_gpois$sims.list$beta0, fit_gpois$sims.list$beta2)
# plot(fit_gpois$sims.list$beta0, fit_gpois$sims.list$beta3)
# plot(fit_gpois$sims.list$beta0, fit_gpois$sims.list$beta4)
```

```{R Visualize Model Fit}
plot(fit_gpois$sims.list$SSEobs,fit_gpois$sims.list$SSEsim,xlab="SSEobs",ylab="SSEsim")
abline(0,1,lwd = 2, col = "red")
print(paste0("P value is: ",round(fit_gpois$mean$p_val, 2)))

```


```{R Create Plots of Posterior Distribution}
# Plot posterior distribution
chains_gpois <- jags_df(fit_gpois)
# Select the chains for our covariates of interest
chains_viol <- chains_gpois %>% select(beta1,beta2,beta3,beta4)
# Rename them to be more interpretable
colnames(chains_viol) <- c("Percent Canopy Landscape",
                           "Percent Shrub/Early Successional Landscape",
                           "Veg SD Residuals",
                           "Percent Shrub/Early Successional Core")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("Percent Canopy Landscape",
                           "Percent Shrub/Early Successional Landscape",
                           "Veg SD Residuals",
                           "Percent Shrub/Early Successional Core"),names_to = "parameter", values_to = "values")

f_stat <- data.frame(
  parameter = c(
    "Percent Canopy Landscape",
    "Percent Shrub/Early Successional Landscape",
    "Veg SD Residuals",
    "Percent Shrub/Early Successional Core"),
  median_value = c(
    paste0("F:",round(fit_gpois$f$beta1,2)),
    paste0("F:",round(fit_gpois$f$beta2,2)),
    paste0("F:",round(fit_gpois$f$beta3,2)),
    paste0("F:",round(fit_gpois$f$beta4,2)))
)

# Create the slab interval plot - FIND THE ACTUAL COLORS FOR THESE
ggplot(data = chains_viol_long, aes(x = values, y = parameter, fill = parameter)) + 
  # Plot posterior distributions
  stat_slabinterval() +
  # Establish colors
  scale_fill_manual(values = c("Percent Canopy Landscape"=palette_8[8], 
                               "Percent Shrub/Early Successional Landscape" = palette_8[6],
                               "Veg SD Residuals"=palette_8[7], 
                               "Percent Shrub/Early Successional Core" = palette_5[5])) +
  # Add a line for 0 to show overlap of posterior
  geom_vline(xintercept = 0) +
  # Remove background color from plots
  theme_minimal() +
  # Turn off the legend
  guides(fill = "none") +
  # Add median values as text labels
  geom_text(data = f_stat, aes(x = 3.5, y = parameter, label = median_value), color = "black", hjust = .6) 
```

```{R}
# Transform median values from posterior distribution into probability 
c <- round(plogis(fit_gpois$q50$beta0), 3)
print(paste0("Baseline number of calls during breeding season: ", c))

b1 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta1), 3)
print(paste0("Percent Canopy Landscape: ", b1))

b2 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta2), 3)
print(paste0("Percent Shrub/Early Successional Landscape: ", b2))

b3 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta3), 3)
print(paste0("Veg SD Residuals: ", b3))

b4 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta4), 3)
print(paste0("Percent Shrub/Early Successional Core: ", b4))
```

```{R}
# Create a matrix of the mcmc chains for each parameter
mat <- cbind(fit_gpois$sims.list$beta0,fit_gpois$sims.list$beta1,fit_gpois$sims.list$beta2,fit_gpois$sims.list$beta3,fit_gpois$sims.list$beta4)
# run a correlation test on the chains - here, I'm looking for values that are larger than other values
r <- cor(mat)
#r
colnames(mat) <- c("psi","percent canopy landscape","% shrub/early successional cover landscape", "veg sd residual", "shrub/early successional cover core")
corrgram(mat, order=TRUE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Parameters")

```


### Interpreting output:

**Strongly significant covariates (CI doesn't overlap 0):** 

* Residuals of all vegetation standard deviation regressed against canopy height: we have no evidence that the true effect of vegetation sd residuals on the strength of use by BBCU is negative. The median estimate for vegetation sd residuals effect transformed into probability space is 0.607, which means that at the average values of every other covariate, for every 1 sd increase in veg sd residuals above the mean (.8 increase above mean value of 0 *not sure if it's helpful to include the values here???*), the count of BBCU calls during the breeding season increases by 60.7%.

* Percent shrub/early successional cover at landscape scale: we have no evidence that the true effect of percent shrub/early successional at landscpae scale is positive. The median estimate for the effect of this covariate transformed into probability space is 0.111, which means that for every 1 sd increase in percent shrub/early successional cover across the landscape (increase of 7.64 percentage points above the mean value of 14.4% cover), the count of BBCU calls during the breeding season decreases by 11.1%. 

* Percent canopy cover at landscape scale: there is a 98% chance that the true effect of percent canopy cover at landscape scale is positive. The median estimate for the effect of this covariate transformed into probability space is 0.436, which means that for every 1 sd increase in percent canopy cover at the landscape scale (increase of 6.8 percentage points above the mean value of 8.2% cover), the count of BBCU calls during the breeding season increases by 43.6%. 

**Weakly significant covariates (F > .70):**

* Percent shrub/early successional cover at core scale: There is a 93% chance that the true effect of percent shrub/early successional cover at the core scale is negative. The median estimate for the effect of this covariate transformed into probability space is 0.169, which means that for every 1 sd increase in percent canopy cover at the core scale (increase of 11 percentage points above the mean value of 18.5% cover), the count of BBCU calls during the breeding season decreases by 16.9%.

```{R, include = FALSE, eval = FALSE}
# Old model for safekeeping

    model {
    for (i in 1:n){
    
    # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
      cov3[i] ~ dnorm(0, 1)
      cov4[i] ~ dnorm(0, 1)
    
      # Method 2: gamma-poisson (this is equivalent to a negative binomial)
      # In this approach, the parameter of interest is the count of days with calls but we're also feeding it the number of days that we recorded 
      log(gamma[i]) = beta0 + beta1 * cov1[i] + beta2 * cov2[i] + beta3 * cov3[i] + beta4 * cov4[i]  
      h[i] ~ dgamma(theta, theta) # Variance in rate parameter
      y[i] ~ dpois(gamma[i] * h[i]) # count drawn from poisson distribution with adjusted rate parameter
      
    }
    # Priors
    theta ~ dgamma(1,1)
    beta0 ~ dnorm(0, 0.01)
    beta1 ~ dnorm(0, 0.01)
    beta2 ~ dnorm(0, 0.01) 
    beta3 ~ dnorm(0, 0.01)
    beta4 ~ dnorm(0, 0.01) 
    
    # Derived values
    # Calculate squared residuals between y[i] and model predicted values of rate parameter gamma[i]*h[i]
    # Simulate new data based on posterior predictive distribution using same rate parameter

    }
```