---
title: "Hab Chap Linear Model Version 7: Gamma-Poisson Paramterization"
author: "Anna Kurtin"
date: "9/13/2024"
output: html_document
---

This is the seventh iteration of the linear model I will be using to test strength of habitat use across sites. Created after my conversation with Thomas R where he explained that I need to be accounting for not only proportion of days with calling but also how many days there are for each site. Last model didn't converge so I'm going to try to remove the covariate for year 

### Model structure



**Handling of NAs (only occur in habitat covs):** Imputation 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(beepr)
library(corrgram)
library(ggdist)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```


### Visualize Data and Colinearity 

```{R Read in Data}
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/Linear_Model/HabChap_22-23_DaysCalls_HabCovs_9-12.csv")
# Create a year covariate
full_dat <- full_dat %>% mutate(yr_val = ifelse(year == 2023, 1, 0))
```

### Set up model 

```{R Format Data for JAGS}
# Filter out just days that had calls
full_dat <- full_dat %>% filter(pct_days_wcall > 0)
```

```{R Set up JAGS Data, echo = TRUE}
# Create a list of data for JAGS
jags_data <- list(
  # Percentage of days with bbcu 
  y = full_dat$days_wcall,
  # Covariates with a positive effect
  # % canopy landscape
  cov1 = full_dat$pct_can_landsc,
  # residual veg sd
  cov2 = full_dat$veg_sd_resid,
  # year
  cov3 = full_dat$yr_val,
  n = nrow(full_dat)
)

# Set initial values 
init_func <- function(){
  list(
    beta0 = rnorm(1, 0, 1), 
    beta1 = rnorm(1, 0, 1),
    beta2 = rnorm(1, 0, 1),
    beta3 = rnorm(1, 0, 1)
  )
}
```

```{R Create Model Structure, eval = FALSE}
sink("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLMod7_GamPois.jags")
cat("
    model {
    for (i in 1:n){
    
    # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
    
      # Method 2: gamma-poisson (this is equivalent to a negative binomial)
      # In this approach, the parameter of interest is the count of days with calls but we're also feeding it the number of days that we recorded 
      log(gamma[i]) = beta0 + beta1 * cov1[i] + beta2 * cov2[i] 
      h[i] ~ dgamma(theta, theta)
      y[i] ~ dpois(gamma[i] * h[i])
      
    }

    theta ~ dgamma(1,1)
    beta0 ~ dnorm(0, 0.01)
    beta1 ~ dnorm(0, 0.01)
    beta2 ~ dnorm(0, 0.01)

    }
    ",fill = TRUE)
sink()

```


```{R, results = FALSE, eval = FALSE}
fit_gpois <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLMod7_GamPois.jags",
                 parameters.to.save = c("beta0","beta1","beta2"),
                 n.iter = 20000, 
                 n.burnin = 10000, 
                 n.chains = 3,
                 n.thin = 10,
                 inits = init_func)
beep()
saveRDS(fit_gpois,"C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LMod7_GamPois.Rdata")
```
```{R Read in Model}
fit_gpois <- readRDS("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LMod7_GamPois.Rdata")
```

```{R Evaluate Model}
summary(fit_gpois)
tracedens_jags(fit_gpois, parmfrow = c(2,2)) 
```

*Thoughts and questions*

* Originally when I ran them, they were still not looking good, even after taking the year cvariate out. 

* I changed the precision on the priors from 0.1 to 0.01tried to decrease the precision on the priors, the effective sample size is just within the good range now but traceplots still don't look good. 