---
title: "Hab Chap Linear Model Version 15: Gamma-Poisson Paramterization on Two-Week Period During Peak Calling"
author: "Anna Kurtin"
date: "10/30/2024"
output: html_document
---

This is the fifteenth iteration of the linear model I will be using to test strength of habitat use across sites. Using the gamma-poisson distribution to parameterize the response variable to account for not only how many days with calling but also how many days there are for each site. Trying to include all of the data including the zeros and all of the covariates of interest. Only looking at data from the period between July 1st and July 15th so that standardizing effort, adding in covariate for the number of days recorded at a site.

This current version includes more covariates that affect the number of calls detected, including the signal to noise ratio (background dB - I checked my emails with Tessa from April 23rd ish 2024 and found that the way I calculated background dB is sound, I left the default which was the calculate the dB relative to the loudest sound within the file) and veg. I realized that at some point during model iteration I stopped including conifer species richness so I'm going to go back and include this.

*Current version of the model*

### Model structure:

$$ c_i \sim Poisson(\gamma_i * h_i) $$

$$ h_i \sim Gamma(\theta,\theta) $$

$$ \theta \sim Gamma(1, 1) $$

$$ log(\gamma_i) = \beta_0 + \beta_1 * cov1 + \beta_2 * cov2 + \beta_3 * cov3 + \beta_4 * cov4 +\beta_5 * cov5 + \beta_6 *cov6 + \beta_7 * cov7 $$

$$ c_i: \text{Number of calls at a site}$$

$$ \beta_1: \text{Percent canopy cover at lanscape scale}$$

$$ \beta_2: \text{Percent shrub/early successional cover at landscape scale} $$

$$ \beta_3: \text{Vegetation sd residuals at core area scale} $$

$$ \beta_4: \text{Percent shrub/early successional cover at core area scale} $$
$$ \beta_5: \text{Native Conifer Spp Richness} $$


$$ \beta_6: \text{Combined days of recording}$$

$$ \beta_7: \text{SNR of Sound Files} $$

$$ \beta_8: \text{vegetation density} $$
$$ 
\log(\gamma_i) = \beta_0 + \beta_1 * \text{% canopy cover landscape}_i + \beta_2 * \text{% SES cover landscape}_i + \beta_3 * \text{vegetation complexity core}_i + \beta_4 * \text{% SES cover core}_i + \beta_5 * \text{conifer tree richness point}_i + \beta_6 * \text{recording days}_i + \beta_7 * \text{background noise}_i + \beta_8 * \text{vegetation density}_i
$$
**Handling of NAs (only occur in habitat covs):** Imputation for habitat covariates (sites with no LiDAR data), no missing data for call counts


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(beepr)
library(corrgram)
library(ggdist)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```


### Visualize Data and Colinearity 

```{R Read in Data}
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/Linear_Model/DaysCalls_14DayPer_HabCovsSCALED_22-23_10-30.csv")

hist(full_dat$days_wcall, main = "Number of Days with Calling Across Sites", xlab = "Total Days with Calling", col = cuckoo_palette[1])
```


```{R Visualize Calls Over Dates, message = FALSE, warning = FALSE}
# From Plot_BBCU_calls_per_date_22-23.R
cnn_23 <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Classifier_Results/Model2.0/Outputs/2023_AllCollab_topclips_filteredPBYBCU_5-27.csv")
cnn_23$date_formatted <- as.Date(cnn_23$date_formatted)
# Establish start and end periods for periods of interest
start_period <- as.Date("2023-07-01")
end_period <- as.Date("2023-07-15")
all23 <- cnn_23 %>% group_by(site_id, date_formatted) %>% summarize(bbcu = sum(annotation))
# Looking at distribution of days with calling
all23 <- all23 %>% group_by(date_formatted) %>% summarize(num_calls = sum(bbcu))
start_23 <- min(all23$date_formatted)
end_23 <- max(all23$date_formatted)
all23 %>% ggplot() + 
  geom_bar(aes(x = date_formatted, y = num_calls), stat = "identity", fill = cuckoo_palette[1])+
  scale_x_date(limits = c(start_23, end_23), date_breaks = "4 days", date_labels = "%b %d") +
  scale_y_continuous(limits = c(0, 13), breaks = seq(0,12, by = 2)) +
  labs(x = "Date", y = "Number of Calls", title = "Daily Call Rates 2023", subtitle = "Max 4 Calls Per Day Per Site") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 60,hjust = 1))+
  geom_vline(xintercept = start_period) +
  geom_vline(xintercept = end_period)


cnn_22 <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Classifier_Results/Model2.0/Outputs/2022_AllCollab_topclips_filteredPBYBCU_5-27.csv")
cnn_22$date_formatted <- as.Date(cnn_22$date_formatted)
# Establish periods of interest
start_period <- as.Date("2022-07-01")
end_period <- as.Date("2022-07-15")
all22 <- cnn_22 %>% group_by(site_id, date_formatted) %>% summarize(bbcu = sum(annotation))
all22 <- all22 %>% group_by(date_formatted) %>% summarize(num_calls = sum(bbcu))
start_22 <- as.Date("2022-06-01")
end_22 <- as.Date("2022-08-15")
all22 %>% ggplot() + 
  geom_bar(aes(x = date_formatted, y = num_calls), stat = "identity", fill = cuckoo_palette[1]) +
  scale_x_date(limits = c(start_22, end_22), date_breaks = "4 days", date_labels = "%b %d") +
  scale_y_continuous(limits = c(0, 13), breaks = seq(0,12, by = 2)) +
  labs(x = "Date", y = "Number of Calls", title = "Daily Call Rates 2022", subtitle = "Max 4 Calls Per Day Per Site") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 60,hjust = 1)) +
  geom_vline(xintercept = start_period) +
  geom_vline(xintercept = end_period)

```

```{R Visualize Habitat Covs, message = FALSE, warning = FALSE}
# Read in unscaled data and visualize the distribution
dat_us <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/Linear_Model/DaysCalls_14DayPer_HabCovsUNSCALED_22-23_10-30.csv")

# Percent Canopy Landscape (palette_8[8])
dat_us %>% ggplot() +
  geom_point(aes(x = pct_can_landsc, y = days_wcall), col = palette_8[8])+
  labs(x = "% Canopy at Landscape Scale", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
# Percent Open Shrub Landscape palette_8[6]
dat_us %>% ggplot() +
  geom_point(aes(x = pct_openshrub_landsc, y = days_wcall), col = palette_8[6])+
  labs(x = "% Shrub/Early Successional Cover at Landscape Scale", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
# Veg SD Residuals "Veg SD Residuals"=palette_8[7]
dat_us %>% ggplot() +
  geom_point(aes(x = veg_sd_resid, y = days_wcall), col = palette_8[7])+
  labs(x = "Veg St Dev Residuals from Canopy Height", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
# Percent Openshrub Core "Percent Shrub/Early Successional Core" = palette_5[5]
dat_us %>% ggplot() +
  geom_point(aes(x = pct_openshrub_core, y = days_wcall), col = palette_8[5])+
  labs(x = "% Shrub/Early Successional Cover at Core Scale", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
# Conifer Spp Richness
dat_us %>% ggplot() +
  geom_point(aes(x = ctree_spp_rich, y = days_wcall), col = palette_8[1])+
  labs(x = "Conifer Tree Species Richness", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
# Combined days of recording palette_5[1]
dat_us %>% ggplot() +
  geom_point(aes(x = combined_days_rec, y = days_wcall), col = palette_5[1])+
  labs(x = "Recording Days at Site", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
# Background noise (SNR)
dat_us %>% ggplot() +
  geom_point(aes(x = avg_db, y = days_wcall), col = palette_5[2])+
  labs(x = "Background Noise at Site", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
# Veg density
dat_us %>% ggplot() +
  geom_point(aes(x = avg_vegdense, y = days_wcall), col = palette_5[3])+
  labs(x = "Vegetation Density", y = "Count of Days with Calls") +
  scale_y_continuous(limits = c(0,10), breaks = seq(0,10, by = 2)) +
  theme_minimal()
```

*Ignore the warnings below*

```{R, warnings = FALSE, message = FALSE}
corrdat <- full_dat %>% select(pct_can_landsc, pct_openshrub_landsc, veg_sd_resid, pct_openshrub_core, ctree_spp_rich, combined_days_rec, avg_db, avg_vegdense)
corrgram(corrdat, order=FALSE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Habitat Metrics")
```

### Set up model 

```{R Set up JAGS Data, echo = TRUE}
# Create a list of data for JAGS
jags_data <- list(
  # Percentage of days with bbcu 
  y = full_dat$days_wcall,
  # % canopy landscape
  cov1 = full_dat$pct_can_landsc,
  # % open shrub landscape
  cov2 = full_dat$pct_openshrub_landsc,
  # residual veg sd
  cov3 = full_dat$veg_sd_resid,
  # % open shrub core
  cov4 = full_dat$pct_openshrub_core,
  # Conifer spp richness
  cov5 = full_dat$ctree_spp_rich,
  # Recording days at site
  cov6 = full_dat$combined_days_rec,
  # background db
  cov7 = full_dat$avg_db,
  # vegetation density
  cov8 = full_dat$avg_vegdense,
  # number of days recorded at each site
  n = nrow(full_dat)
)
  
# Set initial values 
init_func <- function(){
  list(
    beta0 = rnorm(1, 0, 1), 
    beta1 = rnorm(1, 0, 1),
    beta2 = rnorm(1, 0, 1),
    beta3 = rnorm(1, 0, 1),
    beta4 = rnorm(1, 0, 1),
    beta5 = rnorm(1, 0, 1),
    beta6 = rnorm(1, 0, 1),
    beta7 = rnorm(1, 0, 1),
    beta8 = rnorm(1, 0, 1)
  )
}
```

```{R Create Model Structure, eval = FALSE, echo = TRUE}
sink("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLMod15_GamPois.jags")
cat("
    model {
    for (i in 1:n){
    
    # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
      cov3[i] ~ dnorm(0, 1)
      cov4[i] ~ dnorm(0, 1)
      cov5[i] ~ dnorm(0, 1)
      cov8[i] ~ dnorm(0, 1)
    
      # Method 2: gamma-poisson (this is equivalent to a negative binomial)
      # In this approach, the parameter of interest is the count of days with calls but we're also feeding it the number of days that we recorded 
      log(gamma[i]) = beta0 + beta1 * cov1[i] + beta2 * cov2[i] + beta3 * cov3[i] + beta4 * cov4[i] + beta5 * cov5[i] + beta6 * cov6[i] + beta7 * cov7[i] + beta8 * cov8[i] 
      h[i] ~ dgamma(theta, theta) # Variance in rate parameter
      y[i] ~ dpois(gamma[i] * h[i]) # count drawn from poisson distribution with adjusted rate parameter
    
      # Squared residuals for observed data
      presi[i] <- pow((y[i] - gamma[i]*h[i]),2)
      # Simulate new data
      y_new[i] ~ dpois(gamma[i]*h[i])
      # Squared residuals for simulated data
      presi_new[i] <- pow((y_new[i] - gamma[i]*h[i]),2)
      
    }
    # Priors
    theta ~ dgamma(1,1)
    beta0 ~ dnorm(0, 0.01)
    beta1 ~ dnorm(0, 0.01)
    beta2 ~ dnorm(0, 0.01) 
    beta3 ~ dnorm(0, 0.01)
    beta4 ~ dnorm(0, 0.01) 
    beta5 ~ dnorm(0, 0.01)
    beta6 ~ dnorm(0, 0.01) 
    beta7 ~ dnorm(0, 0.01)
    beta8 ~ dnorm(0, 0.01)
    
    # Derived values
    SSEobs <- sum(presi[])
    SSEsim <- sum(presi_new[])
    # Bayesian p-value: proportion of times SSEsim > SSEobserved
    p_val <- step(SSEsim - SSEobs)

    }
    ",fill = TRUE)
sink()

```


```{R, results = FALSE, eval = FALSE, echo = TRUE}
fit_gpois <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLMod15_GamPois.jags",
                 parameters.to.save = c("beta0",
                                        "beta1",
                                        "beta2",
                                        "beta3",
                                        "beta4", 
                                        "beta5",
                                        "beta6",
                                        "beta7",
                                        "beta8",
                                        "SSEobs",
                                        "SSEsim", 
                                        "p_val"),
                 n.iter = 45000, 
                 n.burnin = 20000, 
                 n.chains = 3,
                 n.thin = 10,
                 inits = init_func)
beep()
saveRDS(fit_gpois,"C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LMod15_GamPois_14Day.Rdata")
```
```{R Read in Model}
fit_gpois <- readRDS("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LMod15_GamPois_14Day.Rdata")
```

```{R Evaluate Model}
summary(fit_gpois)
tracedens_jags(fit_gpois, parmfrow = c(2,2)) 
```

```{R Visualize Model Fit}
par(mfrow = c(1,1))
plot(fit_gpois$sims.list$SSEobs,fit_gpois$sims.list$SSEsim,xlab="SSEobs",ylab="SSEsim")
abline(0,1,lwd = 2, col = "red")
print(paste0("P value is: ",round(fit_gpois$mean$p_val, 2)))

```


```{R Create Plots of Posterior Distribution}
# Plot posterior distribution
chains_gpois <- jags_df(fit_gpois)
# Select the chains for our covariates of interest
chains_viol <- chains_gpois %>% select(beta1,beta2,beta3,beta4, beta5, beta6, beta7, beta8)
# Rename them to be more interpretable
colnames(chains_viol) <- c("Percent Canopy Landscape",
                           "Percent SES Landscape",
                           "Veg SD Residuals",
                           "Percent SES Core",
                           "Conifer Spp Richness",
                           "Recording Days at Site",
                           "Background Noise",
                           "Veg Density")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("Percent Canopy Landscape",
                           "Percent SES Landscape",
                           "Veg SD Residuals",
                           "Percent SES Core",
                           "Conifer Spp Richness",
                           "Recording Days at Site",
                           "Background Noise",
                           "Veg Density"),names_to = "parameter", values_to = "values")

f_stat <- data.frame(
  parameter = c(
    "Percent Canopy Landscape",
                           "Percent SES Landscape",
                           "Veg SD Residuals",
                           "Percent SES Core",
                            "Conifer Spp Richness",
                           "Recording Days at Site",
                           "Background Noise",
                           "Veg Density"),
  median_value = c(
    paste0("F:",round(fit_gpois$f$beta1,2)),
    paste0("F:",round(fit_gpois$f$beta2,2)),
    paste0("F:",round(fit_gpois$f$beta3,2)),
    paste0("F:",round(fit_gpois$f$beta4,2)),
    paste0("F:",round(fit_gpois$f$beta5,2)),
    paste0("F:",round(fit_gpois$f$beta6,2)),
    paste0("F:",round(fit_gpois$f$beta7,2)),
    paste0("F:",round(fit_gpois$f$beta8,2)))
)

# Create the slab interval plot
ggplot(data = chains_viol_long, aes(x = values, y = parameter, fill = parameter)) + 
  # Plot posterior distributions
  stat_slabinterval() +
  # Establish colors
  scale_fill_manual(values = c("Percent Canopy Landscape"=palette_8[8], 
                               "Percent SES Landscape" = palette_8[6],
                               "Veg SD Residuals"=palette_8[7], 
                               "Percent SES Core" = palette_5[5],
                               "Conifer Spp Richness"=palette_8[1],
                               "Recording Days at Site" = palette_5[1],
                               "Background Noise" = palette_5[2],
                               "Veg Density" = palette_5[3])) +
  # Add a line for 0 to show overlap of posterior
  geom_vline(xintercept = 0) +
  # Remove background color from plots
  theme_minimal() +
  # Turn off the legend
  guides(fill = "none") +
  # Add median values as text labels
  geom_text(data = f_stat, aes(x = 3.5, y = parameter, label = median_value), color = "black", hjust = .6) 
```

## Median effects
```{R median effect sizes}
# Just median value not plogis 
print(paste0("Percent Canopy Landscape: ", fit_gpois$q50$beta1))

print(paste0("Percent Shrub/Early Successional Landscape: ", fit_gpois$q50$beta2))

print(paste0("Veg SD Residuals: ", fit_gpois$q50$beta3))

print(paste0("Percent Shrub/Early Successional Core: ", fit_gpois$q50$beta4))

print(paste0("Conifer Spp Richness: ", fit_gpois$q50$beta5))

print(paste0("Recording Days at Site: ", fit_gpois$q50$beta6))

print(paste0("Background Noise at Site: ", fit_gpois$q50$beta7))

print(paste0("Veg Density at Site: ", fit_gpois$q50$beta8))
```


```{R Median effects OLD, include = FALSE}
# Transform median values from posterior distribution into probability 
c <- round(plogis(fit_gpois$q50$beta0), 3)
print(paste0("Baseline number of calls during breeding season: ", c))

b1 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta1), 3)
# test
#b1 <- round(plogis(fit_gpois$q50$beta0) + plogis(fit_gpois$q50$beta1), 3)
print(paste0("Percent Canopy Landscape: ", b1))

b2 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta2), 3)
# difference between just plogis of interecept and plogis of intercept and covariate 
# just raw median values give us the info we want 
# test
hist(fit_gpois$sims.list$beta2)
b2 <- round(plogis(fit_gpois$q50$beta0) + plogis(fit_gpois$q50$beta2), 3)
print(paste0("Percent Shrub/Early Successional Landscape: ", b2))

b3 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta3), 3)
print(paste0("Veg SD Residuals: ", b3))

b4 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta4), 3)
print(paste0("Percent Shrub/Early Successional Core: ", b4))

b5 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta5), 3)
print(paste0("Conifer Spp Richness: ", b5))

b6 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta6), 3)
print(paste0("Recording Days at Site: ", b6))

b7 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta7), 3)
print(paste0("Background Noise at Site: ", b7))

b8 <- round(plogis(fit_gpois$q50$beta0 + fit_gpois$q50$beta8), 3)
print(paste0("Veg Density at Site: ", b8))
```

```{R}
# Create a matrix of the mcmc chains for each parameter
mat <- cbind(fit_gpois$sims.list$beta0,
             fit_gpois$sims.list$beta1,
             fit_gpois$sims.list$beta2,
             fit_gpois$sims.list$beta3,
             fit_gpois$sims.list$beta4,
             fit_gpois$sims.list$beta5,
             fit_gpois$sims.list$beta6,
             fit_gpois$sims.list$beta7,
             fit_gpois$sims.list$beta8)
# run a correlation test on the chains - here, I'm looking for values that are larger than other values
r <- cor(mat)
#r
colnames(mat) <- c("psi",
                   "percent canopy landscape",
                   "% shrub/early successional cover landscape", 
                   "veg sd residual", 
                   "shrub/early successional cover core",
                   "conifer spp rich",
                   "recording days at site",
                   "background noise",
                   "veg density")
corrgram(mat, order=FALSE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Parameters")

```


### Interpreting output:

**Strongly significant covariates (F statistic > 0.90):** 

* Vegetation complexity: We have no evidence that the effect of vegetation complexity on intensity of use is negative ( F = 1). The median estimate for the effect of vegetation complexity on intensity of use of the site is 0.35, which means that at the mean values of the other covariates, for every 1 sd increase in vegetation complexity above the mean (.83 increase over mean of 0), the number of calls at a site increases by .35. 

* Recording days at site: We have no evidence that the effect of the cumulative number of days recorded by all ARUs at the site is negative (F = .99). The median estimate for the effect of recording days on intensity of the use of the site is 0.29, which means that for every 1 sd increase in the cumulative days recorded at the site (13 days increase over 24.6 days or the addition of approximately one more ARU), the number of calls at a site increases by .29.

* Veg density around the monitor: We are 91% sure that the true effect of veg density on intensity of use is positive (F = 0.91). The median estimate for the effect of vegetation density on intensity of use is 0.191, which means that for every 1 sd increase in vegetation density (0.24 increase over mean of 0.29), the number of calls increases by 0.081. Could mention in manuscript that we can't exactly separate out whether this affects how many were detected or how many were truly given. We expected this to have an effect on acoustic attenuation but it looks like it's having a stronger effect on presence at the site (probably measuring the same thing as veg complexity and percent canopy landscape)

* Percent Shrub/Early Successional Cover at Landscape Scale: We are 96% sure that the true effect of shrub/early successional cover on intensity of use is negative (F = .96). The median estimate for the effect of shrub/early succesional cover at the landscape scale on intensity of use is 0.081, which means that for every 1 sd increase in the percent cover (7.4% increase over mean of 14.5%), the number of calls at a site decreases by .081.

* Percent Shrub/Early Successional Cover at Core Scale: We are 93% sure that the true effect of shrub/early successional cover at the core scale on intensity of use is negative (F = .93). The median estimate for the effect of shrub/early successional cover at the core scale on intensity of use is 0.081, which means that for every 1 sd increase in the percent cover over the mean (11.0% increase over mean of 18.4%), the number of calls at a site decreases by .081. 

**Weakly significant covariates (0.70 < F < 0.90):**

* Percent canopy cover at landscape scale: We are 76% sure that the true effect of percent canopy cover at the landscape scale on intensity of use is positive (F = .76). The median estimate for the effect of canopy cover at the landsdcape scale is 0.185, which means that for every 1 sd increase in canopy cover above the mean (6.8% increase over mean of 8.6%), the number of calls at a site increases by 0.185.

* Background Noise: We are 79% sure that the true effect of background noise on intensity of use is negative (F = 0.79). The median estimate for the effect of background noise on intensity of use is 0.108, which means that for every 1 sd increase in background noise (3.57 dB increase over mean of -61.46), the number of calls increases by 0.081. 

* Native Conifer Species Richness: We are 89% sure that the effect of conifer species richness on intensity of use is negative (F = 0.89). The median estimate for the effect of background noise on intensity of use is 0.065, which means that for every 1 sd increase in conifer species richness (0.51 species increase over mean of 0.19 species), the number of calls increases by 0.081.

**Lingering thoughts and questions:**

* What does posterior intercept of -1.71 mean? plogis this gives us 0.15. This seems very low but is because we only had 23 days with calls and 110 sites without calls, so our "average" per site is going to be very small. 

* Do I need to scale my response variable as well? I don't think so.
