---
title: "Hab Chap Linear Model Final 2"
author: "Anna Kurtin"
date: "9/3/2024"
output: html_document
---

This is the second iteration of the poisson model I will be using to test strength of habitat use across sites. I tried looking at number of days with a cuckoo vocalization at all sites (since p* is high so we don't need to account for detection) but based on Final 1, the negative binomial parameterization of my model only works on data with % of days with BBCU > 0, so I separated out these days. Since I'm only looking at points with cuckoos present, I thought it didn't make sense to include the habitat covariates that had a negative effect on presence at the site, since the cuckoos are only inhabiting the sites with low percent subcanopy on landscape scale, low percent subcanopy on core scale, and zero conifer tree species richness, so there won't be enough variation in these points to model. Also with this data I only have 32 data points so can only look at 1-3 covariates and have decent power to detect an effect. Therefore, I'm only including the habitat covariates from the occupancy scale models with an f statistic >.9 and a positive effect on probability of use. 

### Model structure

$$
\theta \sim NegBinomial(\gamma_0 + \gamma_{1} + \gamma_{2})
$$

$$ \gamma_{1}: \text{percent canopy cover on a landscape scale} $$

$$ \gamma_{2}: \text{veg sd residuals on a core scale} $$


**Handling of NAs (only occur in habitat covs):** Imputation 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jagsUI)
library(rjags)
library(tidyverse)
library(jagshelper)
library(ggplot2)
library(beepr)
library(patchwork)
library(ggdist)
library(corrgram)
source("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/5_Visualization/Create_HexCodes_CuckooColorBlind.R")
```

### Visualize Data and Colinearity 

```{R Read in Data}
full_dat <- read.csv("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/Data/Habitat_Model_Covariates/Linear_Model/HabChap_22-23_DaysCalls_HabCovs.csv")
# Round the percentage of days with calls
full_dat$pct_days_wcall <- round(full_dat$pct_days_wcall,0)
```

*How valid is it to only focus on covariates with a positive effect based on our data?*

To include these data and still have the power to detect an effect, we'd need to reparameterize our model to include zeros (see ChatGPT prompt for transforming the data and using a beta distribution). 

```{R Conifer Spp Richness}
ggplot(full_dat) + geom_point(aes(x = ctree_spp_rich, y = pct_days_wcall), size = 3, col = palette_5[1]) + 
  labs(x = "Conifer Tree Species Richness", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Pct Canopy Landsape}
ggplot(full_dat) + geom_point(aes(x = pct_can_landsc, y = pct_days_wcall), size = 3, color = palette_5[2]) + 
  labs(x = "% Canopy 1 km Radius", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Pct Suanopy Landsape}
ggplot(full_dat) + geom_point(aes(x = pct_subcan_landsc, y = pct_days_wcall), size = 3, color = palette_5[3]) + 
  labs(x = "% Subcanopy 1 km Radius", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Veg SD Residuals}
ggplot(full_dat) + geom_point(aes(x = veg_sd_resid, y = pct_days_wcall), size = 3, color = palette_5[4]) + 
  labs(x = "All Vegetation St Dev Residuals on Canopy Height", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Percent Subcanopy Core}
ggplot(full_dat) + geom_point(aes(x = pct_subcan_core, y = pct_days_wcall), size = 3, color = palette_5[5]) + 
  labs(x = "% Subcanopy 130 m Radius", y = "% of Days With Calls") +
  theme_minimal()
```

```{R Chunk Out Data}
# The only thing that was different from our original model was the percentage of days with calls was always > 0, trying to redo this to see if I can get the model to converge this way
## if we needed to parse down the number of covariates we have we could kick out conifer tree spp richness since it's negatively associated with use at all
full_dat <- full_dat %>% filter(pct_days_wcall > 0)
```

```{R Look at Correlations, warnings = FALSE, message = FALSE}
corrdat <- full_dat %>% select(pct_can_landsc, veg_sd_resid)
corrgram(corrdat, order=TRUE, lower.panel=panel.cor,
         upper.panel=panel.pts, text.panel=panel.txt,
         main="Correlations in Habitat Metrics")
```


### Set up model 

```{R Format Data for JAGS}
# Create a list of data for JAGS
jags_data <- list(
  # Percentage of days with bbcu 
  days = full_dat$pct_days_wcall,
  # % canopy landscape
  cov1 = full_dat$pct_can_landsc,
  # residual veg sd
  cov2 = full_dat$veg_sd_resid,
  n_unit = nrow(full_dat)
)

# Set initial values 
init_func <- function(){
  list(
    a0 = rnorm(1, 0, 1),
    a1 = rnorm(1, 0, 1),
    a2 = rnorm(1, 0, 1)
  )
}
```

```{R Create Linear Model, echo = TRUE, eval = FALSE}
cat("
  model{
        # Priors
    a0 ~ dnorm(0, 1)
    a1 ~ dnorm(0, 1)
    a2 ~ dnorm(0, 1)
    sigma ~ dunif(0,10)
    tau <- 1/ (sigma*sigma)
    r ~ dunif(0,10) # prior for the dispersion parameter on negative binomial
  
    # Likelihood
    # Loop through each sampling unit
    for(i in 1:n_unit){
      # Impute missing habitat data
      cov1[i] ~ dnorm(0, 1)
      cov2[i] ~ dnorm(0, 1)
  
      days[i] ~ dnegbin(p[i], r)  # changed this to negative binomial from dpois()
      p[i] <- r / (r + lambda[i]) # Compute probability parameter for negative binomial using lambda (mean) and r (dispersion), I thought moments for negative binomial are mean and dispersion, not probability and dispersion, but I'm not sure if R takes things differently 
      log(lambda[i]) <- a0 + a1*cov1[i] + a2*cov2[i] + eps[i]
      eps[i] ~ dnorm(0, tau)
    }
    
    # Derived parameters - add in Bayesian p value here
    
  }
  ", file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLinearModFinal2.txt")
```

```{R Run Model, eval = FALSE, results = FALSE}
fit_lmF2 <- jags(data = jags_data, 
                 model.file = "C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Model_Structure_Files/JAGS_HabLinearModFinal2.txt",
                 parameters.to.save = c("a0", "a1", "a2"),
                 n.iter = 10000, 
                 n.burnin = 4000, 
                 n.chains = 3,
                 n.thin = 2,
                 inits = init_func)
beep()
saveRDS(fit_lmF2,"C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LModFinal2.Rdata")
```

```{R}
fit_lmF2 <- readRDS("C:/Users/annak/OneDrive/Documents/UM/Research/Coding_Workspace/Cuckoo-Research/R_Scripts/2_Analyses/Habitat_Chapter/Poisson_Model/Models_Ran_Outputs/LModFinal2.Rdata")
```

```{R Evaluate Model}
summary(fit_lmF2)
tracedens_jags(fit_lmF2, parmfrow = c(2,2))
```

Traceplots still look a little thin? Why is this?

$$ \gamma_{1}: \text{percent canopy cover on a landscape scale} $$

$$ \gamma_{2}: \text{veg sd residuals on a core scale} $$

### Examine model fit:

```{R Make Inference on P Value, include = FALSE, eval = FALSE}
plot(fit_lmF1$sims.list$SSEobs,fit_lmF1$sims.list$SSEsim,xlab="SSEobs",ylab="SSEsim")
abline(0,1,lwd = 2, col = "red")
print(paste0("P value is: ",round(fit_BF1$mean$p_val, 2)))
```


### Posterior distributions and F statistics:

```{R Create Plots of Posterior Distribution}
# Plot posterior distribution
chains_lmf2 <- jags_df(fit_lmF2)
# Select the chains for our covariates of interest
chains_viol <- chains_lmf2 %>% select(a1,a2)
# Rename them to be more interpretable
colnames(chains_viol) <- c("% Canopy Cover Landsc","Veg SD Resid")
# Pivot this longer so that we can visualize it
chains_viol_long <- chains_viol %>% pivot_longer(cols = c("% Canopy Cover Landsc","Veg SD Resid"),names_to = "parameter", values_to = "values")

f_stat <- data.frame(
  parameter = c("% Canopy Cover Landsc","Veg SD Resid"),
  median_value = c(paste0("F: ",round(fit_lmF2$f$a1,2)), paste0("F: ",round(fit_lmF2$f$a2,2)))
)

# Create the slab interval plot
ggplot(data = chains_viol_long, aes(x = values, y = parameter, fill = parameter)) + 
  # Plot posterior distributions
  stat_slabinterval() +
  # Establish colors
  scale_fill_manual(values = c("% Canopy Cover Landsc" = palette_5[2], "Veg SD Resid" = palette_5[4])) +
  # Add a line for 0 to show overlap of posterior
  geom_vline(xintercept = 0) +
  # Remove background color from plots
  theme_minimal() +
  # Turn off the legend
  guides(fill = "none") +
  # Add median values as text labels
  geom_text(data = f_stat, aes(x = 3.5, y = parameter, label = median_value), color = "black", hjust = .6)  
```

### Median effect sizes: 

```{R Transform Parameter Estimates}
# Transform median values from posterior distribution into probability 
a0_hat <- round(plogis(fit_lmF2$q50$a0), 3)
print(paste0("Percentage days of calling at mean values: ", a0_hat))

a1 <- round(plogis(fit_lmF2$q50$a0 + fit_lmF2$q50$a1), 3)
print(paste0("Conifer Spp Richness: ", a1))

a2 <- round(plogis(fit_lmF2$q50$a0 + fit_lmF2$q50$a2), 3)
print(paste0("% Canopy landscape: ", a2))
```

### Interpreting Output:

**Strongly significant covariates (CI doesn't overlap 0): **

*So far none*

**Weakly significant covariates (F > .70):** 

*How to interpret these results?*
